CREATE TABLE patient (
        PatientID INTEGER PRIMARY KEY AUTOINCREMENT,
        Age INTEGER,
        Gender TEXT,
        PrimaryDiagnosis TEXT,
        LengthOfStay INTEGER,
        PreviousAdmissions INTEGER,
        Medication TEXT,
        DischargeStatus TEXT,
        Readmission30Days INTEGER
    );

INSERT INTO patient (Age, Gender, PrimaryDiagnosis, LengthOfStay, PreviousAdmissions, Medication, DischargeStatus, Readmission30Days) VALUES
(43, 'Male', 'Kidney Disease', 2, 3, 'Antibiotic', 'Discharged', 0),
(58, 'Male', 'Asthma', 12, 2, 'Insulin', 'Left Against Medical Advice', 0),
(73, 'Male', 'Pneumonia', 11, 3, 'Steroid', 'Discharged', 1),
(80, 'Male', 'Diabetes', 9, 3, 'Dialysis', 'Left Against Medical Advice', 0),
(65, 'Female', 'Pneumonia', 7, 0, 'Antiviral', 'Transferred', 1),
(74, 'Female', 'Hypertension', 10, 3, 'Steroid', 'Transferred', 1),
(76, 'Male', 'Kidney Disease', 4, 1, 'Steroid', 'Discharged', 1),
(89, 'Female', 'Diabetes', 4, 4, 'Diuretic', 'Transferred', 1),
(38, 'Female', 'COPD', 5, 2, 'Dialysis', 'Discharged', 1),
(38, 'Female', 'Asthma', 8, 5, 'Inhaler', 'Transferred', 0),
(72, 'Male', 'Heart Failure', 8, 0, 'Insulin', 'Left Against Medical Advice', 0),
(26, 'Female', 'Pneumonia', 6, 2, 'Dialysis', 'Discharged', 0),
(45, 'Female', 'Asthma', 13, 0, 'Antiviral', 'Transferred', 1),
(62, 'Male', 'Diabetes', 4, 5, 'Insulin', 'Transferred', 1),
(62, 'Female', 'Asthma', 7, 5, 'Inhaler', 'Transferred', 0),
(87, 'Female', 'Liver Disease', 7, 3, 'Inhaler', 'Left Against Medical Advice', 1),
(41, 'Male', 'Pneumonia', 8, 1, 'Inhaler', 'Discharged', 0),
(51, 'Male', 'Kidney Disease', 12, 4, 'Antibiotic', 'Discharged', 1),
(85, 'Female', 'Liver Disease', 10, 3, 'Insulin', 'Transferred', 0),
(41, 'Female', 'Heart Failure', 9, 1, 'Diuretic', 'Left Against Medical Advice', 0),
(76, 'Female', 'Asthma', 2, 4, 'Antibiotic', 'Transferred', 0),
(71, 'Female', 'Liver Disease', 7, 2, 'Antiviral', 'Left Against Medical Advice', 1),
(84, 'Male', 'Asthma', 9, 5, 'ACE Inhibitor', 'Discharged', 1),
(36, 'Male', 'Hypertension', 12, 5, 'Antibiotic', 'Transferred', 1),
(28, 'Male', 'Heart Failure', 2, 1, 'Insulin', 'Transferred', 1),
(52, 'Female', 'Diabetes', 5, 0, 'Antiviral', 'Discharged', 0),
(45, 'Female', 'Liver Disease', 7, 3, 'Antibiotic', 'Transferred', 0),
(20, 'Male', 'Kidney Disease', 12, 2, 'Inhaler', 'Transferred', 0),
(41, 'Male', 'Liver Disease', 9, 5, 'Antiviral', 'Left Against Medical Advice', 0),
(33, 'Male', 'Asthma', 6, 2, 'Antibiotic', 'Left Against Medical Advice', 1),
(76, 'Male', 'Kidney Disease', 11, 2, 'Antibiotic', 'Discharged', 0),
(77, 'Female', 'Hypertension', 2, 2, 'Dialysis', 'Transferred', 0),
(65, 'Female', 'Asthma', 14, 4, 'Antibiotic', 'Left Against Medical Advice', 0),
(80, 'Female', 'Asthma', 12, 0, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(35, 'Male', 'Pneumonia', 3, 5, 'Steroid', 'Left Against Medical Advice', 1),
(71, 'Male', 'Hypertension', 2, 1, 'Steroid', 'Left Against Medical Advice', 1),
(79, 'Male', 'Hypertension', 4, 3, 'Steroid', 'Left Against Medical Advice', 1),
(46, 'Female', 'Heart Failure', 4, 1, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(39, 'Female', 'Hypertension', 14, 5, 'Steroid', 'Transferred', 1),
(85, 'Female', 'COPD', 10, 4, 'Inhaler', 'Discharged', 1),
(38, 'Male', 'Diabetes', 3, 5, 'Antibiotic', 'Discharged', 0),
(48, 'Female', 'Hypertension', 13, 1, 'Diuretic', 'Left Against Medical Advice', 0),
(26, 'Male', 'Diabetes', 5, 0, 'ACE Inhibitor', 'Transferred', 0),
(35, 'Male', 'Hypertension', 12, 2, 'Steroid', 'Discharged', 0),
(20, 'Male', 'Hypertension', 7, 3, 'Diuretic', 'Transferred', 0),
(51, 'Male', 'Kidney Disease', 12, 3, 'Antiviral', 'Discharged', 0),
(44, 'Female', 'COPD', 12, 4, 'Antiviral', 'Transferred', 1),
(64, 'Female', 'Diabetes', 2, 1, 'Steroid', 'Transferred', 0),
(63, 'Male', 'Hypertension', 3, 0, 'Insulin', 'Transferred', 0),
(37, 'Female', 'Asthma', 8, 3, 'ACE Inhibitor', 'Discharged', 0),
(39, 'Female', 'Asthma', 14, 3, 'Antibiotic', 'Left Against Medical Advice', 1),
(29, 'Male', 'Liver Disease', 11, 1, 'ACE Inhibitor', 'Transferred', 1),
(26, 'Female', 'Kidney Disease', 5, 1, 'ACE Inhibitor', 'Transferred', 1),
(40, 'Female', 'COPD', 6, 0, 'Antiviral', 'Left Against Medical Advice', 0),
(67, 'Male', 'Kidney Disease', 13, 0, 'ACE Inhibitor', 'Transferred', 1),
(78, 'Female', 'Liver Disease', 4, 3, 'Diuretic', 'Discharged', 0),
(87, 'Male', 'Heart Failure', 11, 4, 'Dialysis', 'Discharged', 1),
(26, 'Female', 'Diabetes', 5, 2, 'Dialysis', 'Left Against Medical Advice', 0),
(71, 'Male', 'Asthma', 11, 1, 'Diuretic', 'Left Against Medical Advice', 0),
(45, 'Male', 'Pneumonia', 13, 2, 'Dialysis', 'Transferred', 0),
(79, 'Female', 'Pneumonia', 6, 2, 'Inhaler', 'Discharged', 0),
(45, 'Female', 'Asthma', 14, 2, 'Antibiotic', 'Left Against Medical Advice', 0),
(20, 'Female', 'COPD', 8, 4, 'Antibiotic', 'Transferred', 1),
(20, 'Male', 'Diabetes', 2, 0, 'Antiviral', 'Left Against Medical Advice', 1),
(68, 'Female', 'Kidney Disease', 4, 1, 'Inhaler', 'Discharged', 1),
(54, 'Female', 'COPD', 2, 3, 'Diuretic', 'Discharged', 1),
(75, 'Male', 'Liver Disease', 10, 3, 'Insulin', 'Discharged', 0),
(39, 'Male', 'Asthma', 8, 1, 'Insulin', 'Discharged', 0),
(64, 'Male', 'Kidney Disease', 11, 2, 'Diuretic', 'Left Against Medical Advice', 1),
(40, 'Male', 'Heart Failure', 6, 2, 'Steroid', 'Left Against Medical Advice', 1),
(40, 'Female', 'Diabetes', 2, 3, 'Antiviral', 'Left Against Medical Advice', 1),
(89, 'Male', 'COPD', 6, 5, 'Inhaler', 'Left Against Medical Advice', 0),
(74, 'Male', 'COPD', 8, 2, 'Dialysis', 'Transferred', 1),
(47, 'Female', 'Pneumonia', 14, 3, 'Insulin', 'Transferred', 1),
(37, 'Female', 'Kidney Disease', 10, 2, 'Antiviral', 'Discharged', 0),
(25, 'Male', 'Heart Failure', 14, 0, 'Antibiotic', 'Discharged', 1),
(35, 'Male', 'Hypertension', 10, 5, 'Diuretic', 'Left Against Medical Advice', 1),
(90, 'Female', 'Diabetes', 14, 4, 'Antiviral', 'Left Against Medical Advice', 1),
(69, 'Female', 'Heart Failure', 2, 4, 'ACE Inhibitor', 'Discharged', 0),
(38, 'Male', 'Kidney Disease', 10, 1, 'Insulin', 'Discharged', 1),
(26, 'Male', 'Hypertension', 9, 1, 'Antibiotic', 'Left Against Medical Advice', 0),
(88, 'Female', 'Heart Failure', 3, 4, 'Diuretic', 'Discharged', 1),
(70, 'Female', 'COPD', 12, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(90, 'Female', 'Kidney Disease', 8, 5, 'Insulin', 'Left Against Medical Advice', 1),
(85, 'Male', 'COPD', 12, 5, 'Steroid', 'Discharged', 1),
(88, 'Male', 'Kidney Disease', 5, 0, 'Steroid', 'Left Against Medical Advice', 0),
(76, 'Female', 'Hypertension', 9, 5, 'Diuretic', 'Left Against Medical Advice', 0),
(64, 'Male', 'COPD', 4, 4, 'Dialysis', 'Discharged', 1),
(78, 'Male', 'Heart Failure', 14, 4, 'Steroid', 'Transferred', 1),
(90, 'Female', 'Pneumonia', 6, 2, 'ACE Inhibitor', 'Transferred', 1),
(38, 'Male', 'Pneumonia', 14, 1, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(25, 'Female', 'Kidney Disease', 11, 3, 'Antiviral', 'Discharged', 1),
(64, 'Female', 'Hypertension', 9, 0, 'Insulin', 'Transferred', 1),
(34, 'Male', 'Kidney Disease', 3, 3, 'Diuretic', 'Transferred', 0),
(76, 'Female', 'Liver Disease', 10, 3, 'Steroid', 'Transferred', 1),
(73, 'Male', 'Kidney Disease', 13, 3, 'Inhaler', 'Transferred', 0),
(69, 'Male', 'Liver Disease', 2, 2, 'Dialysis', 'Discharged', 1),
(20, 'Male', 'Pneumonia', 11, 2, 'Inhaler', 'Transferred', 1),
(63, 'Female', 'Diabetes', 11, 1, 'Inhaler', 'Left Against Medical Advice', 1),
(28, 'Male', 'Kidney Disease', 8, 3, 'Diuretic', 'Discharged', 0),
(58, 'Male', 'Kidney Disease', 2, 4, 'Dialysis', 'Left Against Medical Advice', 1),
(77, 'Female', 'Hypertension', 3, 4, 'Antibiotic', 'Discharged', 0),
(87, 'Male', 'Hypertension', 5, 2, 'Diuretic', 'Transferred', 1),
(35, 'Male', 'Heart Failure', 3, 1, 'Insulin', 'Left Against Medical Advice', 0),
(41, 'Male', 'Asthma', 6, 1, 'Antiviral', 'Transferred', 0),
(89, 'Female', 'Hypertension', 12, 0, 'Steroid', 'Discharged', 0),
(73, 'Male', 'Asthma', 13, 5, 'Insulin', 'Transferred', 1),
(37, 'Male', 'Kidney Disease', 5, 5, 'Steroid', 'Discharged', 0),
(84, 'Female', 'COPD', 12, 2, 'Insulin', 'Discharged', 0),
(89, 'Female', 'Kidney Disease', 3, 1, 'Antibiotic', 'Left Against Medical Advice', 1),
(26, 'Male', 'Heart Failure', 3, 1, 'Insulin', 'Left Against Medical Advice', 1),
(26, 'Male', 'Diabetes', 2, 1, 'ACE Inhibitor', 'Discharged', 1),
(56, 'Female', 'Asthma', 10, 4, 'Steroid', 'Transferred', 1),
(26, 'Female', 'Pneumonia', 7, 4, 'Antiviral', 'Discharged', 1),
(29, 'Male', 'COPD', 9, 4, 'Antiviral', 'Discharged', 1),
(39, 'Female', 'Asthma', 5, 1, 'Diuretic', 'Discharged', 0),
(38, 'Female', 'Asthma', 2, 3, 'Insulin', 'Left Against Medical Advice', 1),
(52, 'Male', 'Liver Disease', 14, 2, 'Antibiotic', 'Discharged', 1),
(23, 'Female', 'Kidney Disease', 7, 3, 'Dialysis', 'Discharged', 0),
(50, 'Male', 'Heart Failure', 5, 4, 'Diuretic', 'Left Against Medical Advice', 1),
(56, 'Male', 'COPD', 6, 0, 'Dialysis', 'Discharged', 0),
(37, 'Male', 'Asthma', 3, 5, 'Steroid', 'Discharged', 1),
(59, 'Female', 'Liver Disease', 12, 3, 'Dialysis', 'Transferred', 0),
(47, 'Male', 'Hypertension', 13, 5, 'Diuretic', 'Transferred', 0),
(53, 'Female', 'Kidney Disease', 6, 1, 'Inhaler', 'Transferred', 0),
(27, 'Female', 'Hypertension', 2, 0, 'Diuretic', 'Transferred', 1),
(30, 'Male', 'Diabetes', 4, 1, 'Diuretic', 'Left Against Medical Advice', 0),
(76, 'Female', 'Kidney Disease', 6, 4, 'Insulin', 'Discharged', 1),
(22, 'Male', 'Kidney Disease', 6, 3, 'Antibiotic', 'Discharged', 0),
(58, 'Female', 'Pneumonia', 6, 5, 'Antibiotic', 'Discharged', 0),
(44, 'Female', 'Pneumonia', 4, 0, 'Antibiotic', 'Transferred', 1),
(22, 'Male', 'Heart Failure', 4, 0, 'Insulin', 'Left Against Medical Advice', 1),
(85, 'Female', 'COPD', 2, 4, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(90, 'Male', 'Asthma', 11, 1, 'Inhaler', 'Left Against Medical Advice', 0),
(73, 'Female', 'Diabetes', 10, 0, 'Diuretic', 'Discharged', 0),
(48, 'Male', 'Asthma', 3, 3, 'Dialysis', 'Left Against Medical Advice', 0),
(65, 'Female', 'Pneumonia', 9, 1, 'ACE Inhibitor', 'Transferred', 0),
(35, 'Female', 'COPD', 6, 5, 'Diuretic', 'Transferred', 1),
(36, 'Male', 'Diabetes', 13, 3, 'Antibiotic', 'Discharged', 0),
(60, 'Male', 'Hypertension', 2, 5, 'Insulin', 'Transferred', 1),
(39, 'Male', 'Pneumonia', 3, 5, 'Antibiotic', 'Left Against Medical Advice', 0),
(44, 'Male', 'Liver Disease', 5, 4, 'Insulin', 'Discharged', 1),
(35, 'Male', 'Hypertension', 3, 3, 'Diuretic', 'Left Against Medical Advice', 0),
(84, 'Female', 'Pneumonia', 14, 4, 'Dialysis', 'Left Against Medical Advice', 1),
(20, 'Male', 'Asthma', 14, 5, 'Insulin', 'Transferred', 1),
(67, 'Male', 'Liver Disease', 13, 0, 'Inhaler', 'Discharged', 0),
(45, 'Female', 'Kidney Disease', 7, 3, 'Inhaler', 'Left Against Medical Advice', 1),
(33, 'Male', 'Hypertension', 5, 4, 'Inhaler', 'Discharged', 0),
(52, 'Male', 'COPD', 10, 2, 'Diuretic', 'Discharged', 1),
(55, 'Female', 'Liver Disease', 2, 4, 'Diuretic', 'Transferred', 1),
(34, 'Female', 'Heart Failure', 11, 2, 'Diuretic', 'Transferred', 0),
(88, 'Male', 'Diabetes', 4, 2, 'Antibiotic', 'Left Against Medical Advice', 1),
(79, 'Female', 'Kidney Disease', 6, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(45, 'Female', 'COPD', 3, 0, 'Steroid', 'Transferred', 1),
(73, 'Female', 'Pneumonia', 13, 4, 'Dialysis', 'Transferred', 0),
(21, 'Female', 'Pneumonia', 11, 5, 'Insulin', 'Discharged', 0),
(21, 'Female', 'Liver Disease', 10, 4, 'Inhaler', 'Discharged', 1),
(53, 'Male', 'Heart Failure', 12, 1, 'ACE Inhibitor', 'Discharged', 1),
(28, 'Female', 'Heart Failure', 8, 0, 'Diuretic', 'Left Against Medical Advice', 0),
(78, 'Male', 'Pneumonia', 3, 4, 'Antiviral', 'Left Against Medical Advice', 0),
(49, 'Male', 'Kidney Disease', 2, 3, 'Insulin', 'Left Against Medical Advice', 1),
(26, 'Female', 'Pneumonia', 2, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(79, 'Male', 'COPD', 6, 1, 'Insulin', 'Transferred', 0),
(79, 'Female', 'Kidney Disease', 11, 0, 'ACE Inhibitor', 'Transferred', 1),
(69, 'Female', 'Liver Disease', 8, 1, 'ACE Inhibitor', 'Transferred', 0),
(50, 'Male', 'Liver Disease', 10, 0, 'Insulin', 'Discharged', 0),
(47, 'Female', 'Pneumonia', 8, 5, 'ACE Inhibitor', 'Discharged', 0),
(63, 'Female', 'Hypertension', 12, 0, 'Antiviral', 'Left Against Medical Advice', 0),
(43, 'Male', 'Kidney Disease', 8, 4, 'Steroid', 'Discharged', 0),
(64, 'Male', 'Diabetes', 13, 3, 'ACE Inhibitor', 'Discharged', 0),
(78, 'Male', 'Asthma', 6, 4, 'Inhaler', 'Transferred', 0),
(63, 'Male', 'Kidney Disease', 14, 1, 'Antibiotic', 'Transferred', 1),
(83, 'Female', 'Pneumonia', 14, 3, 'Steroid', 'Transferred', 1),
(58, 'Male', 'Hypertension', 6, 1, 'Insulin', 'Discharged', 0),
(54, 'Male', 'Pneumonia', 14, 2, 'Insulin', 'Discharged', 1),
(75, 'Female', 'Heart Failure', 13, 1, 'Steroid', 'Transferred', 0),
(39, 'Female', 'Hypertension', 5, 4, 'ACE Inhibitor', 'Discharged', 1),
(56, 'Male', 'Pneumonia', 7, 3, 'Dialysis', 'Left Against Medical Advice', 0),
(68, 'Female', 'Liver Disease', 9, 5, 'Diuretic', 'Transferred', 0),
(80, 'Female', 'Hypertension', 4, 0, 'Inhaler', 'Left Against Medical Advice', 1),
(56, 'Male', 'Kidney Disease', 6, 5, 'Diuretic', 'Transferred', 0),
(60, 'Male', 'Diabetes', 12, 3, 'ACE Inhibitor', 'Discharged', 1),
(84, 'Male', 'Heart Failure', 4, 2, 'Steroid', 'Left Against Medical Advice', 0),
(30, 'Female', 'Kidney Disease', 12, 3, 'Antiviral', 'Left Against Medical Advice', 1),
(64, 'Male', 'Liver Disease', 8, 5, 'Steroid', 'Discharged', 1),
(89, 'Female', 'Kidney Disease', 2, 3, 'Antiviral', 'Discharged', 0),
(48, 'Female', 'Pneumonia', 3, 3, 'Antiviral', 'Discharged', 1),
(31, 'Female', 'COPD', 6, 2, 'Antibiotic', 'Transferred', 0),
(43, 'Male', 'Kidney Disease', 6, 3, 'Antiviral', 'Left Against Medical Advice', 0),
(63, 'Female', 'Heart Failure', 5, 1, 'ACE Inhibitor', 'Transferred', 0),
(28, 'Female', 'Liver Disease', 9, 1, 'Inhaler', 'Transferred', 0),
(47, 'Female', 'Liver Disease', 9, 4, 'Antibiotic', 'Left Against Medical Advice', 1),
(50, 'Male', 'Diabetes', 14, 3, 'Steroid', 'Discharged', 0),
(58, 'Male', 'Hypertension', 6, 4, 'Antibiotic', 'Transferred', 0),
(60, 'Male', 'Hypertension', 7, 0, 'Antiviral', 'Transferred', 0),
(83, 'Female', 'Heart Failure', 6, 5, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(74, 'Female', 'COPD', 3, 3, 'Insulin', 'Transferred', 1),
(73, 'Female', 'Heart Failure', 2, 5, 'Dialysis', 'Discharged', 1),
(39, 'Male', 'Heart Failure', 14, 4, 'Dialysis', 'Transferred', 0),
(42, 'Male', 'Heart Failure', 12, 0, 'Antiviral', 'Transferred', 0),
(77, 'Male', 'COPD', 12, 5, 'Insulin', 'Left Against Medical Advice', 0),
(54, 'Male', 'Pneumonia', 2, 1, 'Inhaler', 'Transferred', 1),
(79, 'Male', 'Liver Disease', 12, 3, 'Inhaler', 'Discharged', 1),
(55, 'Female', 'COPD', 9, 3, 'Antiviral', 'Discharged', 0),
(86, 'Male', 'Asthma', 2, 1, 'Dialysis', 'Left Against Medical Advice', 1),
(67, 'Male', 'Diabetes', 9, 2, 'Antiviral', 'Discharged', 1),
(28, 'Male', 'Diabetes', 5, 5, 'Antiviral', 'Left Against Medical Advice', 0),
(40, 'Male', 'Diabetes', 2, 0, 'ACE Inhibitor', 'Discharged', 0),
(58, 'Female', 'Diabetes', 4, 5, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(77, 'Female', 'Asthma', 10, 2, 'Antibiotic', 'Transferred', 1),
(31, 'Male', 'Asthma', 14, 5, 'Inhaler', 'Left Against Medical Advice', 0),
(40, 'Male', 'Asthma', 9, 5, 'Antibiotic', 'Left Against Medical Advice', 0),
(65, 'Male', 'Liver Disease', 9, 4, 'Antiviral', 'Left Against Medical Advice', 1),
(35, 'Male', 'COPD', 2, 1, 'Diuretic', 'Transferred', 1),
(64, 'Male', 'Diabetes', 8, 3, 'ACE Inhibitor', 'Transferred', 1),
(80, 'Male', 'Kidney Disease', 2, 4, 'Insulin', 'Transferred', 1),
(65, 'Female', 'Hypertension', 8, 0, 'Antibiotic', 'Transferred', 1),
(62, 'Female', 'Kidney Disease', 12, 5, 'Antibiotic', 'Transferred', 1),
(86, 'Male', 'Pneumonia', 3, 2, 'Steroid', 'Left Against Medical Advice', 1),
(74, 'Female', 'Liver Disease', 11, 5, 'Steroid', 'Discharged', 1),
(67, 'Male', 'Liver Disease', 12, 5, 'Antiviral', 'Left Against Medical Advice', 1),
(56, 'Female', 'Liver Disease', 3, 3, 'Insulin', 'Transferred', 1),
(72, 'Male', 'Hypertension', 5, 2, 'Antiviral', 'Left Against Medical Advice', 0),
(58, 'Male', 'Hypertension', 3, 5, 'ACE Inhibitor', 'Discharged', 1),
(58, 'Female', 'Liver Disease', 14, 2, 'Antibiotic', 'Left Against Medical Advice', 1),
(35, 'Female', 'Liver Disease', 8, 5, 'Dialysis', 'Left Against Medical Advice', 1),
(36, 'Male', 'Diabetes', 5, 0, 'Insulin', 'Left Against Medical Advice', 0),
(36, 'Female', 'Diabetes', 2, 1, 'Antibiotic', 'Left Against Medical Advice', 0),
(34, 'Male', 'Heart Failure', 7, 2, 'Antiviral', 'Left Against Medical Advice', 0),
(65, 'Female', 'Hypertension', 7, 4, 'Steroid', 'Transferred', 0),
(82, 'Female', 'Heart Failure', 9, 3, 'Inhaler', 'Discharged', 0),
(40, 'Female', 'Hypertension', 5, 3, 'Dialysis', 'Left Against Medical Advice', 0),
(66, 'Female', 'Heart Failure', 9, 2, 'Inhaler', 'Discharged', 0),
(62, 'Female', 'Pneumonia', 13, 1, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(25, 'Female', 'Liver Disease', 8, 2, 'Inhaler', 'Left Against Medical Advice', 0),
(80, 'Female', 'Diabetes', 13, 0, 'Steroid', 'Left Against Medical Advice', 0),
(81, 'Male', 'Kidney Disease', 8, 1, 'Inhaler', 'Discharged', 1),
(82, 'Male', 'Diabetes', 5, 0, 'Antibiotic', 'Left Against Medical Advice', 0),
(73, 'Male', 'Asthma', 11, 1, 'Antibiotic', 'Transferred', 0),
(63, 'Male', 'Diabetes', 11, 1, 'Inhaler', 'Transferred', 1),
(50, 'Female', 'Diabetes', 6, 3, 'ACE Inhibitor', 'Discharged', 0),
(45, 'Female', 'Hypertension', 13, 3, 'ACE Inhibitor', 'Transferred', 0),
(60, 'Female', 'Pneumonia', 3, 1, 'Steroid', 'Discharged', 0),
(20, 'Female', 'Hypertension', 9, 0, 'Antiviral', 'Transferred', 0),
(60, 'Male', 'COPD', 11, 4, 'ACE Inhibitor', 'Discharged', 0),
(58, 'Female', 'Heart Failure', 13, 1, 'ACE Inhibitor', 'Discharged', 1),
(40, 'Female', 'Heart Failure', 12, 0, 'Insulin', 'Discharged', 0),
(58, 'Male', 'Diabetes', 4, 1, 'Inhaler', 'Transferred', 1),
(86, 'Male', 'Hypertension', 4, 5, 'Dialysis', 'Left Against Medical Advice', 1),
(62, 'Male', 'Heart Failure', 4, 4, 'Antibiotic', 'Transferred', 1),
(27, 'Female', 'Diabetes', 2, 4, 'Insulin', 'Discharged', 1),
(89, 'Female', 'Hypertension', 12, 1, 'Antibiotic', 'Left Against Medical Advice', 1),
(29, 'Female', 'Kidney Disease', 13, 5, 'Antibiotic', 'Discharged', 1),
(23, 'Female', 'COPD', 8, 5, 'Inhaler', 'Transferred', 1),
(73, 'Male', 'Kidney Disease', 2, 1, 'Steroid', 'Left Against Medical Advice', 1),
(34, 'Female', 'Asthma', 2, 1, 'Insulin', 'Discharged', 1),
(49, 'Male', 'Kidney Disease', 4, 1, 'Antibiotic', 'Discharged', 0),
(82, 'Male', 'Liver Disease', 14, 1, 'Steroid', 'Transferred', 1),
(77, 'Female', 'Kidney Disease', 9, 3, 'Diuretic', 'Transferred', 0),
(50, 'Female', 'Asthma', 12, 0, 'Diuretic', 'Discharged', 0),
(70, 'Female', 'Diabetes', 5, 1, 'ACE Inhibitor', 'Transferred', 0),
(64, 'Female', 'Liver Disease', 14, 4, 'Inhaler', 'Discharged', 0),
(21, 'Male', 'Pneumonia', 10, 4, 'ACE Inhibitor', 'Transferred', 1),
(83, 'Female', 'Liver Disease', 12, 4, 'Insulin', 'Discharged', 0),
(53, 'Male', 'Heart Failure', 7, 5, 'Dialysis', 'Discharged', 1),
(76, 'Male', 'Pneumonia', 6, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(36, 'Male', 'Hypertension', 4, 1, 'Antiviral', 'Transferred', 1),
(86, 'Male', 'COPD', 4, 0, 'Insulin', 'Transferred', 0),
(22, 'Female', 'Heart Failure', 13, 4, 'Antibiotic', 'Left Against Medical Advice', 1),
(65, 'Male', 'Asthma', 13, 5, 'Dialysis', 'Transferred', 0),
(43, 'Female', 'Diabetes', 3, 1, 'ACE Inhibitor', 'Discharged', 1),
(33, 'Female', 'Pneumonia', 14, 2, 'ACE Inhibitor', 'Discharged', 0),
(41, 'Male', 'Heart Failure', 14, 5, 'Diuretic', 'Left Against Medical Advice', 0),
(41, 'Male', 'Heart Failure', 6, 4, 'Antibiotic', 'Transferred', 0),
(44, 'Female', 'Liver Disease', 5, 5, 'Diuretic', 'Left Against Medical Advice', 0),
(72, 'Male', 'Diabetes', 12, 5, 'ACE Inhibitor', 'Transferred', 1),
(61, 'Female', 'Kidney Disease', 3, 0, 'Diuretic', 'Left Against Medical Advice', 0),
(51, 'Male', 'Pneumonia', 8, 1, 'Dialysis', 'Discharged', 1),
(41, 'Female', 'Asthma', 5, 1, 'Dialysis', 'Discharged', 0),
(23, 'Female', 'COPD', 14, 5, 'Antiviral', 'Discharged', 1),
(86, 'Female', 'Kidney Disease', 14, 5, 'Antibiotic', 'Transferred', 0),
(55, 'Male', 'Diabetes', 6, 1, 'Insulin', 'Discharged', 1),
(44, 'Female', 'Asthma', 11, 1, 'Insulin', 'Discharged', 0),
(65, 'Male', 'Diabetes', 4, 1, 'Antiviral', 'Transferred', 1),
(49, 'Female', 'Asthma', 3, 5, 'Steroid', 'Left Against Medical Advice', 0),
(53, 'Female', 'Asthma', 9, 4, 'Inhaler', 'Left Against Medical Advice', 1),
(75, 'Female', 'Liver Disease', 2, 5, 'Antiviral', 'Transferred', 0),
(68, 'Female', 'Kidney Disease', 11, 5, 'Antibiotic', 'Transferred', 0),
(37, 'Male', 'Hypertension', 3, 0, 'Antibiotic', 'Discharged', 0),
(73, 'Female', 'Kidney Disease', 2, 0, 'Steroid', 'Transferred', 0),
(74, 'Female', 'Diabetes', 14, 5, 'Diuretic', 'Left Against Medical Advice', 1),
(21, 'Male', 'Heart Failure', 5, 1, 'Inhaler', 'Discharged', 0),
(52, 'Male', 'Pneumonia', 8, 2, 'Antiviral', 'Transferred', 1),
(49, 'Male', 'Diabetes', 6, 5, 'Antiviral', 'Left Against Medical Advice', 0),
(86, 'Male', 'Pneumonia', 11, 2, 'ACE Inhibitor', 'Discharged', 0),
(30, 'Male', 'Hypertension', 10, 1, 'Inhaler', 'Left Against Medical Advice', 1),
(27, 'Female', 'Hypertension', 11, 0, 'Diuretic', 'Transferred', 1),
(83, 'Female', 'Hypertension', 9, 2, 'Inhaler', 'Left Against Medical Advice', 0),
(46, 'Male', 'Hypertension', 13, 5, 'Inhaler', 'Transferred', 1),
(23, 'Female', 'Asthma', 12, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(32, 'Male', 'Diabetes', 4, 2, 'Antiviral', 'Discharged', 0),
(83, 'Male', 'Diabetes', 14, 1, 'Dialysis', 'Discharged', 1),
(73, 'Male', 'Asthma', 13, 0, 'Diuretic', 'Transferred', 0),
(45, 'Male', 'Diabetes', 4, 5, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(77, 'Male', 'Asthma', 9, 2, 'ACE Inhibitor', 'Transferred', 0),
(58, 'Female', 'Liver Disease', 9, 3, 'ACE Inhibitor', 'Discharged', 0),
(85, 'Female', 'Hypertension', 14, 1, 'Diuretic', 'Left Against Medical Advice', 0),
(44, 'Male', 'COPD', 11, 0, 'Inhaler', 'Discharged', 0),
(89, 'Male', 'COPD', 4, 1, 'Antiviral', 'Transferred', 0),
(41, 'Female', 'Pneumonia', 11, 4, 'Antiviral', 'Left Against Medical Advice', 1),
(54, 'Male', 'Kidney Disease', 12, 0, 'ACE Inhibitor', 'Transferred', 1),
(86, 'Male', 'Heart Failure', 10, 5, 'Inhaler', 'Discharged', 0),
(77, 'Male', 'Heart Failure', 4, 5, 'ACE Inhibitor', 'Discharged', 1),
(20, 'Male', 'Diabetes', 9, 4, 'Diuretic', 'Left Against Medical Advice', 1),
(56, 'Male', 'Liver Disease', 8, 5, 'Antibiotic', 'Left Against Medical Advice', 1),
(79, 'Female', 'Kidney Disease', 7, 0, 'Inhaler', 'Left Against Medical Advice', 1),
(66, 'Female', 'COPD', 10, 3, 'Steroid', 'Transferred', 0),
(24, 'Male', 'Asthma', 2, 5, 'ACE Inhibitor', 'Transferred', 0),
(58, 'Female', 'Diabetes', 3, 2, 'ACE Inhibitor', 'Discharged', 1),
(36, 'Male', 'Kidney Disease', 8, 3, 'Antibiotic', 'Transferred', 0),
(53, 'Male', 'Hypertension', 9, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(41, 'Male', 'Diabetes', 5, 1, 'Antiviral', 'Discharged', 1),
(66, 'Male', 'Hypertension', 14, 1, 'Inhaler', 'Left Against Medical Advice', 1),
(31, 'Male', 'COPD', 11, 1, 'Steroid', 'Transferred', 0),
(33, 'Male', 'Hypertension', 7, 0, 'Insulin', 'Left Against Medical Advice', 1),
(80, 'Male', 'Kidney Disease', 4, 5, 'Antiviral', 'Left Against Medical Advice', 1),
(81, 'Male', 'Diabetes', 3, 5, 'Steroid', 'Transferred', 0),
(25, 'Female', 'Heart Failure', 7, 4, 'Inhaler', 'Discharged', 0),
(43, 'Female', 'Diabetes', 7, 1, 'Steroid', 'Transferred', 1),
(58, 'Female', 'Diabetes', 9, 5, 'Antibiotic', 'Transferred', 1),
(20, 'Male', 'Heart Failure', 5, 4, 'Inhaler', 'Discharged', 0),
(57, 'Male', 'Kidney Disease', 5, 0, 'Inhaler', 'Transferred', 0),
(42, 'Male', 'Diabetes', 9, 4, 'Antibiotic', 'Discharged', 0),
(78, 'Female', 'Asthma', 11, 5, 'Steroid', 'Discharged', 0),
(69, 'Female', 'COPD', 3, 3, 'Inhaler', 'Left Against Medical Advice', 0),
(87, 'Male', 'Liver Disease', 3, 0, 'Insulin', 'Discharged', 0),
(85, 'Female', 'Hypertension', 11, 2, 'Steroid', 'Discharged', 1),
(61, 'Male', 'COPD', 2, 5, 'Diuretic', 'Transferred', 0),
(88, 'Female', 'Hypertension', 10, 5, 'ACE Inhibitor', 'Transferred', 0),
(38, 'Female', 'Pneumonia', 2, 3, 'Antiviral', 'Discharged', 0),
(56, 'Female', 'Pneumonia', 5, 0, 'Steroid', 'Discharged', 0),
(25, 'Female', 'Diabetes', 5, 4, 'Insulin', 'Transferred', 0),
(32, 'Female', 'Asthma', 11, 2, 'Dialysis', 'Discharged', 0),
(64, 'Female', 'Heart Failure', 10, 3, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(63, 'Female', 'Asthma', 5, 3, 'Insulin', 'Discharged', 0),
(79, 'Male', 'Hypertension', 9, 4, 'Dialysis', 'Transferred', 0),
(67, 'Male', 'COPD', 8, 1, 'Antiviral', 'Discharged', 1),
(24, 'Female', 'Pneumonia', 7, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(40, 'Female', 'Hypertension', 4, 2, 'Antiviral', 'Left Against Medical Advice', 1),
(46, 'Male', 'Diabetes', 2, 1, 'Steroid', 'Left Against Medical Advice', 0),
(51, 'Female', 'Pneumonia', 4, 2, 'Steroid', 'Left Against Medical Advice', 0),
(67, 'Male', 'COPD', 12, 5, 'Steroid', 'Discharged', 0),
(60, 'Male', 'Liver Disease', 10, 4, 'Inhaler', 'Transferred', 1),
(39, 'Female', 'Liver Disease', 14, 1, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(30, 'Female', 'Hypertension', 11, 0, 'Antibiotic', 'Transferred', 1),
(49, 'Female', 'Heart Failure', 3, 0, 'Antibiotic', 'Discharged', 1),
(74, 'Female', 'Heart Failure', 10, 2, 'Steroid', 'Discharged', 0),
(40, 'Female', 'Asthma', 4, 5, 'Antiviral', 'Transferred', 1),
(54, 'Female', 'Asthma', 2, 5, 'Inhaler', 'Transferred', 1),
(41, 'Female', 'Heart Failure', 9, 2, 'Antibiotic', 'Transferred', 0),
(49, 'Female', 'Kidney Disease', 6, 5, 'Inhaler', 'Transferred', 1),
(37, 'Male', 'Diabetes', 4, 4, 'Steroid', 'Left Against Medical Advice', 0),
(59, 'Female', 'Heart Failure', 10, 0, 'Antibiotic', 'Discharged', 1),
(76, 'Male', 'Pneumonia', 6, 5, 'Inhaler', 'Transferred', 0),
(20, 'Female', 'Kidney Disease', 6, 4, 'Insulin', 'Transferred', 1),
(36, 'Male', 'Diabetes', 13, 0, 'Dialysis', 'Left Against Medical Advice', 1),
(73, 'Female', 'Hypertension', 6, 4, 'Steroid', 'Discharged', 0),
(84, 'Female', 'Liver Disease', 11, 1, 'Insulin', 'Left Against Medical Advice', 1),
(79, 'Female', 'Liver Disease', 12, 3, 'Steroid', 'Left Against Medical Advice', 0),
(75, 'Female', 'Asthma', 4, 3, 'ACE Inhibitor', 'Transferred', 1),
(59, 'Male', 'Heart Failure', 11, 2, 'Antibiotic', 'Discharged', 1),
(80, 'Male', 'Liver Disease', 8, 3, 'Antiviral', 'Left Against Medical Advice', 0),
(23, 'Female', 'Diabetes', 13, 0, 'Antibiotic', 'Transferred', 0),
(83, 'Female', 'Asthma', 9, 0, 'Inhaler', 'Discharged', 0),
(75, 'Male', 'Kidney Disease', 6, 0, 'Antiviral', 'Transferred', 1),
(54, 'Female', 'Kidney Disease', 5, 0, 'Steroid', 'Discharged', 1),
(51, 'Female', 'Diabetes', 14, 0, 'Inhaler', 'Transferred', 1),
(64, 'Male', 'Diabetes', 6, 0, 'Inhaler', 'Discharged', 0),
(31, 'Female', 'Kidney Disease', 13, 5, 'Insulin', 'Transferred', 1),
(51, 'Male', 'Pneumonia', 2, 2, 'Antibiotic', 'Transferred', 1),
(73, 'Male', 'Diabetes', 4, 3, 'Diuretic', 'Discharged', 0),
(61, 'Female', 'Hypertension', 10, 0, 'Dialysis', 'Discharged', 0),
(29, 'Male', 'Diabetes', 10, 3, 'Steroid', 'Transferred', 1),
(20, 'Male', 'Diabetes', 11, 0, 'Steroid', 'Discharged', 0),
(69, 'Male', 'Pneumonia', 6, 1, 'ACE Inhibitor', 'Discharged', 1),
(88, 'Male', 'COPD', 3, 5, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(21, 'Male', 'COPD', 13, 5, 'ACE Inhibitor', 'Discharged', 0),
(34, 'Male', 'Heart Failure', 6, 0, 'Diuretic', 'Discharged', 0),
(54, 'Female', 'Hypertension', 3, 3, 'Antibiotic', 'Left Against Medical Advice', 1),
(42, 'Female', 'COPD', 13, 1, 'Inhaler', 'Left Against Medical Advice', 0),
(46, 'Female', 'Hypertension', 14, 2, 'Dialysis', 'Discharged', 0),
(33, 'Male', 'Hypertension', 7, 0, 'Insulin', 'Discharged', 0),
(38, 'Male', 'COPD', 14, 0, 'Dialysis', 'Transferred', 1),
(56, 'Male', 'Asthma', 10, 5, 'Dialysis', 'Left Against Medical Advice', 0),
(42, 'Female', 'Diabetes', 11, 3, 'Dialysis', 'Discharged', 1),
(33, 'Female', 'Diabetes', 14, 5, 'Antiviral', 'Left Against Medical Advice', 1),
(51, 'Female', 'Diabetes', 9, 3, 'Steroid', 'Left Against Medical Advice', 0),
(53, 'Male', 'Kidney Disease', 10, 4, 'Dialysis', 'Discharged', 1),
(76, 'Female', 'Pneumonia', 7, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(80, 'Female', 'Liver Disease', 11, 4, 'Dialysis', 'Left Against Medical Advice', 0),
(23, 'Female', 'Hypertension', 7, 3, 'Dialysis', 'Left Against Medical Advice', 0),
(27, 'Female', 'Hypertension', 14, 4, 'Insulin', 'Transferred', 0),
(35, 'Male', 'Diabetes', 2, 0, 'Diuretic', 'Left Against Medical Advice', 0),
(76, 'Male', 'Kidney Disease', 9, 3, 'Diuretic', 'Discharged', 1),
(27, 'Female', 'Hypertension', 13, 5, 'Insulin', 'Transferred', 0),
(63, 'Female', 'Pneumonia', 9, 0, 'Inhaler', 'Discharged', 1),
(75, 'Female', 'COPD', 9, 2, 'Antiviral', 'Left Against Medical Advice', 1),
(29, 'Male', 'Liver Disease', 4, 0, 'ACE Inhibitor', 'Discharged', 1),
(73, 'Male', 'Heart Failure', 6, 2, 'Insulin', 'Transferred', 0),
(38, 'Male', 'Hypertension', 7, 2, 'Diuretic', 'Discharged', 0),
(29, 'Male', 'Asthma', 8, 4, 'Inhaler', 'Transferred', 0),
(30, 'Female', 'Pneumonia', 13, 0, 'Antibiotic', 'Discharged', 1),
(20, 'Female', 'Hypertension', 5, 1, 'Antibiotic', 'Discharged', 0),
(30, 'Male', 'COPD', 3, 2, 'Antiviral', 'Transferred', 0),
(51, 'Female', 'Pneumonia', 5, 2, 'Inhaler', 'Transferred', 0),
(66, 'Female', 'Liver Disease', 2, 5, 'Insulin', 'Transferred', 0),
(81, 'Male', 'COPD', 12, 4, 'Steroid', 'Left Against Medical Advice', 1),
(74, 'Female', 'Asthma', 14, 5, 'Steroid', 'Left Against Medical Advice', 1),
(69, 'Female', 'Hypertension', 11, 0, 'Antiviral', 'Left Against Medical Advice', 0),
(75, 'Male', 'Heart Failure', 10, 3, 'Dialysis', 'Discharged', 0),
(25, 'Female', 'Pneumonia', 6, 0, 'Antiviral', 'Transferred', 0),
(70, 'Female', 'Pneumonia', 6, 0, 'Antibiotic', 'Transferred', 0),
(65, 'Male', 'Diabetes', 9, 0, 'Insulin', 'Transferred', 0),
(48, 'Female', 'Liver Disease', 10, 4, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(43, 'Male', 'Diabetes', 4, 5, 'Diuretic', 'Transferred', 1),
(47, 'Male', 'Asthma', 8, 4, 'Antibiotic', 'Transferred', 1),
(80, 'Male', 'Liver Disease', 11, 4, 'Antibiotic', 'Left Against Medical Advice', 0),
(82, 'Male', 'Asthma', 12, 2, 'Antibiotic', 'Left Against Medical Advice', 1),
(28, 'Male', 'Asthma', 4, 3, 'Steroid', 'Transferred', 0),
(34, 'Female', 'Hypertension', 5, 3, 'Insulin', 'Left Against Medical Advice', 0),
(29, 'Female', 'Kidney Disease', 10, 1, 'Antibiotic', 'Transferred', 0),
(52, 'Male', 'Heart Failure', 6, 5, 'Antibiotic', 'Transferred', 1),
(89, 'Male', 'Diabetes', 11, 0, 'Inhaler', 'Left Against Medical Advice', 1),
(36, 'Male', 'Heart Failure', 8, 1, 'Inhaler', 'Transferred', 1),
(73, 'Female', 'COPD', 13, 1, 'ACE Inhibitor', 'Discharged', 0),
(86, 'Male', 'COPD', 12, 2, 'Antiviral', 'Discharged', 1),
(58, 'Female', 'Hypertension', 3, 1, 'Diuretic', 'Left Against Medical Advice', 1),
(72, 'Female', 'COPD', 9, 2, 'Inhaler', 'Left Against Medical Advice', 1),
(84, 'Male', 'Hypertension', 11, 1, 'Steroid', 'Transferred', 0),
(48, 'Male', 'Kidney Disease', 13, 1, 'Insulin', 'Left Against Medical Advice', 0),
(69, 'Female', 'Diabetes', 2, 0, 'ACE Inhibitor', 'Discharged', 1),
(38, 'Female', 'COPD', 6, 3, 'ACE Inhibitor', 'Discharged', 0),
(76, 'Female', 'Heart Failure', 7, 0, 'Insulin', 'Left Against Medical Advice', 0),
(64, 'Female', 'Hypertension', 5, 1, 'Steroid', 'Transferred', 1),
(59, 'Female', 'Liver Disease', 14, 0, 'Steroid', 'Transferred', 1),
(27, 'Male', 'Asthma', 9, 2, 'Steroid', 'Left Against Medical Advice', 0),
(52, 'Male', 'Diabetes', 9, 4, 'Insulin', 'Transferred', 1),
(47, 'Male', 'COPD', 9, 2, 'Insulin', 'Discharged', 1),
(64, 'Male', 'Hypertension', 4, 4, 'Diuretic', 'Left Against Medical Advice', 0),
(63, 'Female', 'Liver Disease', 13, 5, 'Diuretic', 'Transferred', 1),
(54, 'Male', 'Pneumonia', 10, 1, 'Steroid', 'Transferred', 0),
(22, 'Female', 'Heart Failure', 14, 2, 'Dialysis', 'Discharged', 1),
(71, 'Male', 'Diabetes', 12, 4, 'Dialysis', 'Left Against Medical Advice', 1),
(47, 'Male', 'Pneumonia', 6, 0, 'Insulin', 'Transferred', 1),
(75, 'Female', 'Kidney Disease', 12, 4, 'Antiviral', 'Left Against Medical Advice', 0),
(78, 'Male', 'COPD', 6, 4, 'Antibiotic', 'Discharged', 0),
(61, 'Female', 'Pneumonia', 12, 1, 'Steroid', 'Left Against Medical Advice', 1),
(90, 'Male', 'Pneumonia', 6, 2, 'Diuretic', 'Discharged', 0),
(28, 'Female', 'Hypertension', 13, 5, 'Antiviral', 'Discharged', 1),
(58, 'Male', 'Kidney Disease', 5, 1, 'Inhaler', 'Transferred', 0),
(28, 'Female', 'Asthma', 5, 2, 'Antibiotic', 'Left Against Medical Advice', 1),
(53, 'Female', 'Asthma', 13, 4, 'Inhaler', 'Left Against Medical Advice', 0),
(27, 'Female', 'COPD', 10, 5, 'Inhaler', 'Transferred', 0),
(31, 'Male', 'Liver Disease', 5, 5, 'Insulin', 'Discharged', 1),
(54, 'Female', 'COPD', 14, 2, 'Antibiotic', 'Transferred', 0),
(45, 'Female', 'Hypertension', 14, 4, 'Diuretic', 'Left Against Medical Advice', 1),
(22, 'Female', 'Kidney Disease', 11, 1, 'Diuretic', 'Left Against Medical Advice', 0),
(76, 'Female', 'Asthma', 11, 0, 'Insulin', 'Transferred', 0),
(57, 'Female', 'Diabetes', 4, 2, 'Steroid', 'Transferred', 1),
(29, 'Male', 'Pneumonia', 5, 3, 'Steroid', 'Discharged', 0),
(43, 'Male', 'Heart Failure', 3, 4, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(79, 'Female', 'Liver Disease', 2, 4, 'ACE Inhibitor', 'Transferred', 1),
(85, 'Female', 'COPD', 10, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(26, 'Female', 'Kidney Disease', 12, 3, 'Dialysis', 'Left Against Medical Advice', 1),
(89, 'Male', 'Diabetes', 8, 4, 'Antibiotic', 'Left Against Medical Advice', 0),
(48, 'Female', 'Diabetes', 4, 0, 'Dialysis', 'Left Against Medical Advice', 1),
(32, 'Male', 'Heart Failure', 11, 2, 'Inhaler', 'Discharged', 0),
(60, 'Female', 'Diabetes', 10, 3, 'Steroid', 'Left Against Medical Advice', 0),
(50, 'Female', 'Asthma', 3, 1, 'Steroid', 'Left Against Medical Advice', 0),
(73, 'Male', 'Heart Failure', 2, 2, 'Dialysis', 'Discharged', 0),
(21, 'Female', 'Kidney Disease', 8, 2, 'Inhaler', 'Left Against Medical Advice', 1),
(33, 'Female', 'Hypertension', 13, 1, 'Inhaler', 'Left Against Medical Advice', 0),
(70, 'Male', 'Asthma', 10, 3, 'Steroid', 'Discharged', 1),
(35, 'Male', 'Heart Failure', 5, 3, 'Inhaler', 'Left Against Medical Advice', 0),
(84, 'Male', 'Liver Disease', 7, 2, 'Dialysis', 'Discharged', 0),
(79, 'Female', 'Asthma', 4, 2, 'Diuretic', 'Transferred', 1),
(44, 'Male', 'Heart Failure', 2, 0, 'Steroid', 'Discharged', 1),
(34, 'Female', 'Liver Disease', 3, 1, 'Diuretic', 'Left Against Medical Advice', 1),
(85, 'Male', 'Diabetes', 5, 3, 'Antiviral', 'Left Against Medical Advice', 0),
(84, 'Female', 'Asthma', 8, 3, 'ACE Inhibitor', 'Discharged', 1),
(37, 'Female', 'Hypertension', 3, 3, 'Diuretic', 'Discharged', 1),
(81, 'Female', 'Asthma', 8, 2, 'Steroid', 'Transferred', 1),
(49, 'Female', 'COPD', 14, 5, 'Diuretic', 'Discharged', 0),
(69, 'Female', 'Diabetes', 13, 5, 'ACE Inhibitor', 'Transferred', 1),
(42, 'Female', 'COPD', 13, 1, 'Antiviral', 'Left Against Medical Advice', 1),
(28, 'Female', 'Liver Disease', 9, 5, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(84, 'Female', 'Liver Disease', 8, 5, 'Diuretic', 'Left Against Medical Advice', 0),
(62, 'Female', 'Hypertension', 12, 2, 'Insulin', 'Left Against Medical Advice', 0),
(74, 'Female', 'Hypertension', 8, 1, 'Diuretic', 'Left Against Medical Advice', 0),
(49, 'Female', 'Hypertension', 8, 5, 'Insulin', 'Left Against Medical Advice', 1),
(43, 'Male', 'Liver Disease', 13, 3, 'Diuretic', 'Discharged', 0),
(74, 'Female', 'Heart Failure', 10, 0, 'Antiviral', 'Discharged', 1),
(69, 'Female', 'Asthma', 11, 4, 'Insulin', 'Left Against Medical Advice', 0),
(62, 'Female', 'Kidney Disease', 13, 3, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(25, 'Male', 'Asthma', 12, 1, 'Steroid', 'Discharged', 1),
(62, 'Female', 'Asthma', 5, 5, 'Diuretic', 'Transferred', 0),
(80, 'Male', 'Hypertension', 14, 3, 'ACE Inhibitor', 'Transferred', 1),
(68, 'Female', 'Hypertension', 4, 2, 'Dialysis', 'Transferred', 1),
(48, 'Female', 'Pneumonia', 14, 4, 'Insulin', 'Left Against Medical Advice', 1),
(65, 'Female', 'Diabetes', 3, 5, 'Antiviral', 'Transferred', 1),
(44, 'Male', 'Pneumonia', 3, 0, 'Inhaler', 'Left Against Medical Advice', 0),
(80, 'Male', 'COPD', 8, 3, 'Antiviral', 'Transferred', 1),
(51, 'Female', 'Kidney Disease', 4, 4, 'Dialysis', 'Transferred', 1),
(53, 'Male', 'Asthma', 9, 0, 'ACE Inhibitor', 'Transferred', 1),
(59, 'Male', 'Asthma', 3, 5, 'Inhaler', 'Transferred', 0),
(90, 'Female', 'Kidney Disease', 6, 4, 'Antiviral', 'Discharged', 0),
(85, 'Female', 'Hypertension', 12, 5, 'Steroid', 'Transferred', 1),
(33, 'Female', 'Diabetes', 7, 5, 'Diuretic', 'Left Against Medical Advice', 1),
(57, 'Male', 'Hypertension', 12, 4, 'Inhaler', 'Discharged', 0),
(81, 'Female', 'Hypertension', 10, 2, 'Antiviral', 'Transferred', 0),
(74, 'Female', 'Asthma', 13, 3, 'Diuretic', 'Left Against Medical Advice', 0),
(41, 'Female', 'Diabetes', 14, 1, 'Antiviral', 'Left Against Medical Advice', 1),
(24, 'Male', 'Asthma', 2, 1, 'Inhaler', 'Transferred', 1),
(27, 'Male', 'Asthma', 11, 1, 'Diuretic', 'Left Against Medical Advice', 0),
(63, 'Male', 'Liver Disease', 11, 4, 'Inhaler', 'Left Against Medical Advice', 0),
(82, 'Female', 'Kidney Disease', 14, 4, 'Antiviral', 'Left Against Medical Advice', 0),
(79, 'Female', 'Pneumonia', 8, 3, 'Antibiotic', 'Left Against Medical Advice', 1),
(23, 'Female', 'Hypertension', 13, 1, 'Inhaler', 'Left Against Medical Advice', 1),
(53, 'Male', 'Diabetes', 13, 2, 'Insulin', 'Transferred', 0),
(63, 'Female', 'Heart Failure', 12, 4, 'Inhaler', 'Left Against Medical Advice', 0),
(65, 'Male', 'Pneumonia', 8, 2, 'Antibiotic', 'Transferred', 0),
(59, 'Female', 'COPD', 4, 2, 'Insulin', 'Discharged', 1),
(49, 'Female', 'Liver Disease', 8, 3, 'Insulin', 'Transferred', 1),
(69, 'Male', 'COPD', 12, 5, 'Antibiotic', 'Transferred', 0),
(67, 'Female', 'Hypertension', 11, 3, 'Antiviral', 'Left Against Medical Advice', 1),
(79, 'Male', 'Asthma', 10, 1, 'Steroid', 'Transferred', 1),
(86, 'Male', 'COPD', 13, 4, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(55, 'Male', 'Asthma', 10, 1, 'Dialysis', 'Left Against Medical Advice', 0),
(61, 'Male', 'Pneumonia', 6, 4, 'Steroid', 'Discharged', 0),
(73, 'Male', 'Diabetes', 6, 0, 'Steroid', 'Transferred', 1),
(71, 'Female', 'Asthma', 9, 5, 'Antiviral', 'Transferred', 1),
(75, 'Male', 'Kidney Disease', 10, 1, 'Dialysis', 'Left Against Medical Advice', 0),
(48, 'Female', 'Pneumonia', 10, 1, 'Steroid', 'Transferred', 0),
(85, 'Male', 'Hypertension', 14, 2, 'Diuretic', 'Transferred', 1),
(44, 'Male', 'Kidney Disease', 8, 5, 'Diuretic', 'Discharged', 1),
(60, 'Male', 'COPD', 13, 5, 'Antiviral', 'Transferred', 0),
(24, 'Male', 'COPD', 10, 2, 'Diuretic', 'Discharged', 0),
(58, 'Female', 'COPD', 12, 3, 'ACE Inhibitor', 'Discharged', 0),
(52, 'Male', 'Kidney Disease', 11, 0, 'ACE Inhibitor', 'Transferred', 1),
(75, 'Male', 'Hypertension', 14, 5, 'Dialysis', 'Discharged', 1),
(75, 'Male', 'Pneumonia', 9, 3, 'Insulin', 'Discharged', 1),
(61, 'Female', 'Asthma', 12, 0, 'Steroid', 'Discharged', 1),
(50, 'Female', 'Liver Disease', 12, 2, 'Diuretic', 'Left Against Medical Advice', 0),
(87, 'Male', 'Pneumonia', 8, 1, 'Steroid', 'Discharged', 1),
(33, 'Female', 'Diabetes', 10, 4, 'Insulin', 'Left Against Medical Advice', 1),
(44, 'Male', 'Heart Failure', 11, 2, 'Inhaler', 'Discharged', 0),
(73, 'Male', 'Hypertension', 2, 1, 'Dialysis', 'Discharged', 0),
(75, 'Male', 'Asthma', 13, 1, 'Inhaler', 'Transferred', 1),
(65, 'Female', 'Asthma', 3, 1, 'Insulin', 'Discharged', 1),
(55, 'Female', 'Hypertension', 14, 0, 'Antiviral', 'Left Against Medical Advice', 1),
(64, 'Female', 'Pneumonia', 4, 5, 'Dialysis', 'Transferred', 0),
(85, 'Male', 'Asthma', 7, 3, 'Antibiotic', 'Transferred', 0),
(24, 'Female', 'Diabetes', 7, 1, 'Insulin', 'Transferred', 1),
(36, 'Male', 'Pneumonia', 7, 5, 'Inhaler', 'Discharged', 0),
(86, 'Female', 'Asthma', 8, 1, 'Antiviral', 'Discharged', 0),
(58, 'Male', 'Liver Disease', 2, 4, 'Antibiotic', 'Left Against Medical Advice', 0),
(46, 'Female', 'Hypertension', 6, 5, 'Steroid', 'Discharged', 1),
(63, 'Male', 'Hypertension', 8, 2, 'Antibiotic', 'Transferred', 1),
(43, 'Male', 'Diabetes', 3, 4, 'Antibiotic', 'Left Against Medical Advice', 0),
(43, 'Male', 'Kidney Disease', 6, 4, 'Inhaler', 'Left Against Medical Advice', 1),
(45, 'Male', 'Liver Disease', 4, 5, 'Insulin', 'Transferred', 0),
(53, 'Male', 'COPD', 3, 0, 'Inhaler', 'Transferred', 0),
(25, 'Male', 'Liver Disease', 8, 4, 'ACE Inhibitor', 'Transferred', 1),
(67, 'Male', 'Pneumonia', 10, 2, 'Antibiotic', 'Transferred', 1),
(62, 'Female', 'Heart Failure', 13, 4, 'Antibiotic', 'Discharged', 0),
(69, 'Female', 'Diabetes', 10, 0, 'Antibiotic', 'Transferred', 1),
(67, 'Male', 'Kidney Disease', 2, 2, 'Antiviral', 'Transferred', 0),
(68, 'Female', 'Kidney Disease', 2, 4, 'Diuretic', 'Left Against Medical Advice', 0),
(21, 'Female', 'Heart Failure', 5, 4, 'Inhaler', 'Transferred', 0),
(68, 'Female', 'Hypertension', 8, 5, 'Antiviral', 'Transferred', 1),
(59, 'Female', 'Kidney Disease', 3, 5, 'Dialysis', 'Transferred', 1),
(63, 'Male', 'Liver Disease', 4, 4, 'Diuretic', 'Left Against Medical Advice', 0),
(64, 'Female', 'Heart Failure', 13, 0, 'Dialysis', 'Left Against Medical Advice', 0),
(38, 'Female', 'COPD', 14, 4, 'Diuretic', 'Left Against Medical Advice', 1),
(87, 'Male', 'Hypertension', 12, 0, 'Dialysis', 'Discharged', 1),
(23, 'Female', 'Hypertension', 9, 4, 'Insulin', 'Transferred', 0),
(88, 'Male', 'Diabetes', 3, 5, 'Dialysis', 'Discharged', 0),
(48, 'Female', 'Heart Failure', 14, 3, 'Antiviral', 'Discharged', 0),
(26, 'Male', 'Pneumonia', 12, 0, 'Diuretic', 'Transferred', 0),
(29, 'Male', 'COPD', 2, 4, 'Antiviral', 'Discharged', 0),
(49, 'Female', 'Hypertension', 10, 5, 'Dialysis', 'Transferred', 0),
(68, 'Male', 'Asthma', 7, 2, 'Insulin', 'Discharged', 0),
(29, 'Female', 'Asthma', 6, 3, 'Diuretic', 'Transferred', 1),
(28, 'Female', 'Liver Disease', 9, 3, 'Diuretic', 'Left Against Medical Advice', 0),
(35, 'Male', 'Hypertension', 3, 0, 'Antibiotic', 'Discharged', 1),
(54, 'Male', 'Hypertension', 9, 5, 'Inhaler', 'Left Against Medical Advice', 0),
(20, 'Male', 'Liver Disease', 3, 1, 'Antiviral', 'Transferred', 1),
(45, 'Male', 'Heart Failure', 5, 0, 'Insulin', 'Discharged', 1),
(28, 'Female', 'Diabetes', 11, 5, 'Diuretic', 'Left Against Medical Advice', 0),
(44, 'Male', 'Pneumonia', 13, 2, 'ACE Inhibitor', 'Discharged', 0),
(90, 'Female', 'Diabetes', 3, 0, 'ACE Inhibitor', 'Transferred', 1),
(51, 'Female', 'Pneumonia', 3, 3, 'Steroid', 'Left Against Medical Advice', 1),
(89, 'Female', 'Hypertension', 10, 2, 'ACE Inhibitor', 'Discharged', 0),
(90, 'Female', 'Heart Failure', 2, 3, 'ACE Inhibitor', 'Transferred', 1),
(30, 'Female', 'Diabetes', 6, 3, 'Antibiotic', 'Transferred', 1),
(40, 'Male', 'Hypertension', 5, 4, 'Steroid', 'Transferred', 1),
(32, 'Male', 'Asthma', 7, 1, 'Inhaler', 'Discharged', 1),
(39, 'Male', 'Asthma', 5, 5, 'Insulin', 'Transferred', 0),
(24, 'Female', 'Hypertension', 9, 3, 'Antiviral', 'Discharged', 0),
(63, 'Female', 'Pneumonia', 11, 3, 'Steroid', 'Discharged', 1),
(24, 'Female', 'Pneumonia', 12, 2, 'Steroid', 'Left Against Medical Advice', 0),
(84, 'Male', 'Kidney Disease', 7, 4, 'Insulin', 'Left Against Medical Advice', 0),
(50, 'Male', 'Diabetes', 6, 0, 'Dialysis', 'Left Against Medical Advice', 0),
(66, 'Male', 'Kidney Disease', 8, 0, 'Antiviral', 'Discharged', 1),
(72, 'Male', 'Hypertension', 14, 0, 'Antiviral', 'Transferred', 0),
(68, 'Male', 'Diabetes', 13, 2, 'Antiviral', 'Left Against Medical Advice', 0),
(22, 'Male', 'Kidney Disease', 8, 3, 'Steroid', 'Transferred', 1),
(62, 'Female', 'Hypertension', 6, 5, 'Dialysis', 'Discharged', 1),
(86, 'Female', 'Hypertension', 3, 2, 'Insulin', 'Transferred', 0),
(86, 'Male', 'Liver Disease', 11, 0, 'Antiviral', 'Left Against Medical Advice', 1),
(52, 'Male', 'COPD', 13, 0, 'Antibiotic', 'Transferred', 0),
(42, 'Male', 'Hypertension', 11, 4, 'Antiviral', 'Left Against Medical Advice', 1),
(90, 'Female', 'Pneumonia', 12, 1, 'Diuretic', 'Left Against Medical Advice', 1),
(54, 'Female', 'Heart Failure', 4, 4, 'Steroid', 'Transferred', 0),
(47, 'Male', 'Heart Failure', 9, 5, 'Steroid', 'Transferred', 1),
(41, 'Male', 'Kidney Disease', 9, 2, 'Antiviral', 'Discharged', 0),
(71, 'Female', 'COPD', 8, 4, 'Insulin', 'Discharged', 0),
(50, 'Female', 'Pneumonia', 8, 2, 'Dialysis', 'Transferred', 1),
(32, 'Female', 'Asthma', 6, 4, 'Antiviral', 'Left Against Medical Advice', 1),
(35, 'Male', 'Heart Failure', 5, 2, 'Steroid', 'Left Against Medical Advice', 1),
(29, 'Female', 'Heart Failure', 4, 5, 'Diuretic', 'Left Against Medical Advice', 1),
(30, 'Male', 'Diabetes', 10, 4, 'Antiviral', 'Left Against Medical Advice', 0),
(22, 'Male', 'Hypertension', 12, 2, 'Inhaler', 'Left Against Medical Advice', 0),
(64, 'Female', 'Heart Failure', 3, 1, 'Insulin', 'Left Against Medical Advice', 1),
(68, 'Male', 'Asthma', 2, 2, 'Antiviral', 'Discharged', 1),
(52, 'Male', 'Pneumonia', 3, 0, 'Insulin', 'Discharged', 0),
(46, 'Male', 'Heart Failure', 10, 5, 'Dialysis', 'Discharged', 1),
(25, 'Male', 'Asthma', 6, 4, 'ACE Inhibitor', 'Discharged', 1),
(75, 'Female', 'Liver Disease', 5, 5, 'Diuretic', 'Transferred', 1),
(85, 'Male', 'Asthma', 2, 1, 'ACE Inhibitor', 'Discharged', 0),
(43, 'Female', 'COPD', 13, 2, 'Inhaler', 'Transferred', 1),
(46, 'Male', 'COPD', 10, 2, 'Antiviral', 'Transferred', 1),
(27, 'Female', 'Kidney Disease', 3, 3, 'ACE Inhibitor', 'Discharged', 0),
(89, 'Male', 'COPD', 12, 1, 'ACE Inhibitor', 'Transferred', 0),
(20, 'Female', 'COPD', 5, 3, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(34, 'Female', 'Kidney Disease', 13, 1, 'Antibiotic', 'Left Against Medical Advice', 0),
(61, 'Female', 'Liver Disease', 2, 3, 'Steroid', 'Discharged', 0),
(22, 'Male', 'Diabetes', 5, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(46, 'Female', 'Kidney Disease', 2, 4, 'Diuretic', 'Discharged', 1),
(41, 'Female', 'COPD', 14, 2, 'Diuretic', 'Transferred', 0),
(21, 'Female', 'Pneumonia', 9, 5, 'Diuretic', 'Left Against Medical Advice', 0),
(41, 'Female', 'Heart Failure', 7, 3, 'Inhaler', 'Discharged', 0),
(40, 'Female', 'Heart Failure', 11, 2, 'Antiviral', 'Transferred', 1),
(66, 'Female', 'Heart Failure', 11, 5, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(21, 'Male', 'Kidney Disease', 3, 5, 'Inhaler', 'Transferred', 1),
(90, 'Male', 'Liver Disease', 11, 3, 'Insulin', 'Discharged', 1),
(64, 'Female', 'Liver Disease', 12, 0, 'Diuretic', 'Discharged', 1),
(78, 'Male', 'Diabetes', 3, 0, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(70, 'Male', 'Diabetes', 7, 4, 'Dialysis', 'Left Against Medical Advice', 1),
(54, 'Female', 'Diabetes', 12, 1, 'Antibiotic', 'Discharged', 0),
(72, 'Female', 'COPD', 10, 4, 'Antibiotic', 'Transferred', 1),
(44, 'Female', 'Kidney Disease', 6, 5, 'Diuretic', 'Left Against Medical Advice', 1),
(23, 'Female', 'Pneumonia', 5, 3, 'Antibiotic', 'Left Against Medical Advice', 1),
(20, 'Male', 'Kidney Disease', 2, 3, 'Insulin', 'Transferred', 1),
(43, 'Male', 'Hypertension', 8, 4, 'Inhaler', 'Left Against Medical Advice', 0),
(31, 'Female', 'Heart Failure', 13, 1, 'Insulin', 'Left Against Medical Advice', 0),
(29, 'Male', 'Kidney Disease', 14, 3, 'Diuretic', 'Discharged', 0),
(38, 'Female', 'Kidney Disease', 13, 1, 'Dialysis', 'Transferred', 1),
(50, 'Male', 'Kidney Disease', 7, 1, 'Antiviral', 'Transferred', 0),
(89, 'Male', 'Heart Failure', 7, 4, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(21, 'Male', 'Liver Disease', 6, 5, 'Diuretic', 'Left Against Medical Advice', 0),
(89, 'Male', 'Liver Disease', 11, 1, 'Dialysis', 'Left Against Medical Advice', 1),
(80, 'Female', 'Diabetes', 6, 0, 'Dialysis', 'Left Against Medical Advice', 0),
(53, 'Female', 'COPD', 13, 5, 'Antiviral', 'Transferred', 1),
(71, 'Female', 'Heart Failure', 13, 4, 'Insulin', 'Discharged', 1),
(25, 'Male', 'Heart Failure', 10, 3, 'Antibiotic', 'Left Against Medical Advice', 1),
(33, 'Male', 'Diabetes', 6, 0, 'Antiviral', 'Transferred', 0),
(82, 'Female', 'Pneumonia', 5, 3, 'Inhaler', 'Transferred', 0),
(67, 'Male', 'COPD', 13, 5, 'Steroid', 'Transferred', 0),
(37, 'Male', 'Asthma', 7, 2, 'Inhaler', 'Left Against Medical Advice', 1),
(24, 'Male', 'Heart Failure', 2, 2, 'Steroid', 'Left Against Medical Advice', 0),
(58, 'Female', 'COPD', 11, 0, 'Steroid', 'Discharged', 0),
(74, 'Male', 'Asthma', 3, 1, 'Antibiotic', 'Discharged', 0),
(67, 'Female', 'COPD', 9, 0, 'Diuretic', 'Left Against Medical Advice', 0),
(65, 'Female', 'COPD', 6, 0, 'Antiviral', 'Transferred', 1),
(78, 'Female', 'Kidney Disease', 14, 4, 'Steroid', 'Left Against Medical Advice', 0),
(85, 'Male', 'Heart Failure', 7, 3, 'Dialysis', 'Discharged', 1),
(60, 'Male', 'Heart Failure', 10, 3, 'Steroid', 'Discharged', 1),
(24, 'Male', 'Pneumonia', 3, 4, 'Steroid', 'Discharged', 0),
(53, 'Female', 'Kidney Disease', 3, 0, 'Diuretic', 'Transferred', 0),
(30, 'Male', 'Pneumonia', 3, 1, 'ACE Inhibitor', 'Transferred', 0),
(72, 'Male', 'Diabetes', 9, 4, 'Diuretic', 'Transferred', 1),
(77, 'Female', 'Asthma', 7, 1, 'Antiviral', 'Left Against Medical Advice', 1),
(30, 'Female', 'Asthma', 2, 3, 'Insulin', 'Left Against Medical Advice', 0),
(56, 'Female', 'Liver Disease', 7, 0, 'Diuretic', 'Left Against Medical Advice', 0),
(53, 'Female', 'Heart Failure', 5, 4, 'Steroid', 'Left Against Medical Advice', 0),
(51, 'Male', 'Asthma', 9, 3, 'Dialysis', 'Discharged', 0),
(78, 'Female', 'Diabetes', 12, 0, 'Insulin', 'Transferred', 1),
(29, 'Female', 'Pneumonia', 8, 1, 'Inhaler', 'Left Against Medical Advice', 1),
(29, 'Male', 'Pneumonia', 10, 4, 'ACE Inhibitor', 'Transferred', 1),
(30, 'Male', 'Asthma', 3, 0, 'Inhaler', 'Transferred', 1),
(75, 'Male', 'Diabetes', 8, 2, 'Diuretic', 'Transferred', 1),
(79, 'Male', 'COPD', 9, 2, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(76, 'Male', 'Liver Disease', 8, 2, 'Inhaler', 'Left Against Medical Advice', 0),
(52, 'Male', 'Liver Disease', 9, 5, 'Diuretic', 'Transferred', 1),
(77, 'Male', 'Diabetes', 14, 2, 'Diuretic', 'Discharged', 1),
(49, 'Female', 'Liver Disease', 14, 4, 'Steroid', 'Discharged', 1),
(82, 'Male', 'COPD', 2, 1, 'Antibiotic', 'Discharged', 0),
(20, 'Male', 'Liver Disease', 11, 2, 'Diuretic', 'Discharged', 0),
(27, 'Female', 'Kidney Disease', 13, 4, 'Steroid', 'Discharged', 0),
(34, 'Female', 'Asthma', 12, 4, 'Dialysis', 'Transferred', 0),
(54, 'Male', 'Diabetes', 11, 4, 'Antiviral', 'Left Against Medical Advice', 0),
(40, 'Female', 'Kidney Disease', 3, 4, 'Inhaler', 'Discharged', 1),
(83, 'Male', 'Pneumonia', 12, 5, 'Inhaler', 'Discharged', 1),
(43, 'Female', 'Liver Disease', 8, 1, 'Insulin', 'Transferred', 1),
(86, 'Male', 'Kidney Disease', 13, 0, 'Inhaler', 'Discharged', 1),
(55, 'Female', 'COPD', 14, 3, 'Antibiotic', 'Discharged', 0),
(48, 'Female', 'Kidney Disease', 8, 0, 'Dialysis', 'Transferred', 0),
(87, 'Female', 'Liver Disease', 11, 0, 'Diuretic', 'Transferred', 1),
(67, 'Female', 'Pneumonia', 9, 2, 'Inhaler', 'Left Against Medical Advice', 1),
(77, 'Male', 'Kidney Disease', 12, 3, 'Insulin', 'Transferred', 1),
(89, 'Female', 'Hypertension', 11, 5, 'Antiviral', 'Transferred', 0),
(59, 'Female', 'Hypertension', 11, 0, 'Steroid', 'Transferred', 1),
(62, 'Female', 'Asthma', 11, 4, 'Diuretic', 'Discharged', 0),
(81, 'Female', 'Kidney Disease', 2, 1, 'ACE Inhibitor', 'Discharged', 0),
(21, 'Female', 'Heart Failure', 5, 3, 'ACE Inhibitor', 'Discharged', 0),
(89, 'Female', 'Heart Failure', 7, 0, 'Insulin', 'Discharged', 1),
(57, 'Male', 'Diabetes', 8, 1, 'ACE Inhibitor', 'Discharged', 0),
(86, 'Female', 'Asthma', 3, 5, 'Steroid', 'Transferred', 1),
(26, 'Female', 'Diabetes', 2, 3, 'ACE Inhibitor', 'Transferred', 0),
(37, 'Male', 'Pneumonia', 8, 2, 'Steroid', 'Transferred', 1),
(33, 'Female', 'Pneumonia', 5, 4, 'Inhaler', 'Transferred', 0),
(28, 'Female', 'Kidney Disease', 10, 1, 'Inhaler', 'Left Against Medical Advice', 0),
(56, 'Male', 'Kidney Disease', 13, 1, 'Steroid', 'Left Against Medical Advice', 0),
(32, 'Female', 'Pneumonia', 6, 2, 'Inhaler', 'Left Against Medical Advice', 0),
(39, 'Male', 'Kidney Disease', 4, 4, 'Inhaler', 'Transferred', 1),
(36, 'Male', 'Diabetes', 12, 0, 'Steroid', 'Transferred', 0),
(82, 'Male', 'Pneumonia', 4, 5, 'Inhaler', 'Discharged', 1),
(28, 'Male', 'Liver Disease', 2, 3, 'Steroid', 'Transferred', 0),
(87, 'Male', 'Pneumonia', 7, 4, 'Inhaler', 'Discharged', 0),
(71, 'Female', 'Pneumonia', 8, 0, 'Inhaler', 'Discharged', 1),
(79, 'Female', 'Kidney Disease', 14, 3, 'Antiviral', 'Transferred', 0),
(68, 'Female', 'Kidney Disease', 6, 1, 'Antiviral', 'Transferred', 1),
(41, 'Male', 'Heart Failure', 5, 5, 'Insulin', 'Transferred', 1),
(78, 'Male', 'Diabetes', 9, 0, 'ACE Inhibitor', 'Discharged', 1),
(81, 'Female', 'Heart Failure', 13, 2, 'Insulin', 'Transferred', 1),
(33, 'Female', 'Liver Disease', 13, 2, 'Diuretic', 'Discharged', 0),
(51, 'Male', 'Liver Disease', 14, 0, 'Diuretic', 'Discharged', 1),
(25, 'Female', 'COPD', 10, 3, 'Dialysis', 'Left Against Medical Advice', 0),
(79, 'Female', 'Liver Disease', 8, 1, 'Insulin', 'Left Against Medical Advice', 0),
(37, 'Male', 'Asthma', 13, 4, 'Antibiotic', 'Discharged', 1),
(27, 'Female', 'Diabetes', 8, 3, 'ACE Inhibitor', 'Transferred', 0),
(88, 'Male', 'Heart Failure', 3, 2, 'Diuretic', 'Transferred', 0),
(25, 'Female', 'Heart Failure', 3, 1, 'Steroid', 'Left Against Medical Advice', 0),
(61, 'Male', 'Heart Failure', 4, 4, 'Antiviral', 'Transferred', 1),
(38, 'Female', 'Pneumonia', 7, 1, 'Diuretic', 'Left Against Medical Advice', 0),
(43, 'Male', 'Pneumonia', 11, 5, 'Inhaler', 'Transferred', 0),
(81, 'Male', 'Diabetes', 4, 5, 'ACE Inhibitor', 'Discharged', 1),
(72, 'Female', 'Diabetes', 4, 3, 'Antibiotic', 'Left Against Medical Advice', 1),
(75, 'Female', 'Liver Disease', 8, 4, 'Dialysis', 'Left Against Medical Advice', 0),
(79, 'Female', 'Heart Failure', 8, 3, 'Insulin', 'Discharged', 0),
(50, 'Female', 'Kidney Disease', 6, 5, 'Steroid', 'Transferred', 1),
(45, 'Male', 'Pneumonia', 8, 2, 'ACE Inhibitor', 'Transferred', 0),
(20, 'Male', 'Kidney Disease', 11, 4, 'Steroid', 'Discharged', 1),
(85, 'Male', 'Asthma', 9, 3, 'Insulin', 'Left Against Medical Advice', 1),
(47, 'Female', 'Pneumonia', 3, 3, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(46, 'Female', 'Heart Failure', 2, 1, 'Steroid', 'Discharged', 0),
(21, 'Female', 'Kidney Disease', 12, 5, 'Diuretic', 'Transferred', 0),
(68, 'Male', 'Heart Failure', 8, 4, 'Dialysis', 'Discharged', 1),
(20, 'Male', 'Heart Failure', 9, 1, 'Antiviral', 'Left Against Medical Advice', 1),
(59, 'Female', 'Diabetes', 9, 4, 'Antibiotic', 'Left Against Medical Advice', 0),
(65, 'Male', 'Heart Failure', 9, 3, 'Insulin', 'Left Against Medical Advice', 1),
(26, 'Female', 'Hypertension', 7, 3, 'Insulin', 'Left Against Medical Advice', 1),
(43, 'Female', 'Hypertension', 4, 2, 'Antiviral', 'Transferred', 0),
(76, 'Male', 'Diabetes', 6, 2, 'Dialysis', 'Transferred', 1),
(75, 'Female', 'Kidney Disease', 11, 1, 'ACE Inhibitor', 'Discharged', 0),
(72, 'Female', 'Kidney Disease', 6, 1, 'Steroid', 'Transferred', 0),
(56, 'Female', 'Kidney Disease', 4, 0, 'Antiviral', 'Transferred', 0),
(66, 'Female', 'Diabetes', 13, 0, 'Inhaler', 'Discharged', 0),
(61, 'Female', 'Pneumonia', 4, 2, 'Inhaler', 'Transferred', 0),
(64, 'Male', 'COPD', 9, 0, 'Diuretic', 'Left Against Medical Advice', 0),
(54, 'Male', 'Kidney Disease', 10, 0, 'Steroid', 'Left Against Medical Advice', 0),
(33, 'Male', 'Asthma', 7, 5, 'ACE Inhibitor', 'Transferred', 0),
(74, 'Male', 'Hypertension', 2, 2, 'Diuretic', 'Transferred', 0),
(52, 'Male', 'Hypertension', 6, 3, 'Dialysis', 'Transferred', 0),
(57, 'Female', 'COPD', 7, 4, 'Insulin', 'Left Against Medical Advice', 1),
(81, 'Female', 'COPD', 14, 4, 'Antibiotic', 'Transferred', 1),
(56, 'Male', 'Heart Failure', 5, 1, 'Insulin', 'Transferred', 0),
(81, 'Female', 'Asthma', 9, 0, 'Antibiotic', 'Left Against Medical Advice', 1),
(83, 'Male', 'Heart Failure', 6, 4, 'Dialysis', 'Discharged', 0),
(88, 'Female', 'Liver Disease', 10, 1, 'Antiviral', 'Discharged', 0),
(61, 'Female', 'Diabetes', 3, 0, 'Diuretic', 'Transferred', 1),
(61, 'Male', 'Hypertension', 4, 4, 'Antiviral', 'Transferred', 1),
(23, 'Male', 'COPD', 11, 4, 'Antiviral', 'Transferred', 0),
(62, 'Male', 'Asthma', 10, 1, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(68, 'Female', 'Kidney Disease', 13, 3, 'ACE Inhibitor', 'Transferred', 0),
(82, 'Female', 'Kidney Disease', 11, 4, 'Diuretic', 'Discharged', 0),
(28, 'Female', 'Liver Disease', 5, 3, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(37, 'Female', 'COPD', 8, 3, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(89, 'Male', 'Hypertension', 6, 4, 'Antibiotic', 'Discharged', 1),
(41, 'Female', 'Diabetes', 3, 5, 'Steroid', 'Left Against Medical Advice', 0),
(62, 'Male', 'Asthma', 6, 4, 'ACE Inhibitor', 'Transferred', 1),
(31, 'Male', 'Heart Failure', 9, 2, 'Insulin', 'Left Against Medical Advice', 0),
(70, 'Female', 'Kidney Disease', 3, 2, 'Dialysis', 'Discharged', 1),
(27, 'Female', 'Liver Disease', 4, 0, 'Steroid', 'Discharged', 0),
(75, 'Female', 'Kidney Disease', 12, 4, 'Dialysis', 'Left Against Medical Advice', 1),
(41, 'Female', 'Hypertension', 9, 1, 'Inhaler', 'Left Against Medical Advice', 0),
(42, 'Female', 'Kidney Disease', 7, 4, 'ACE Inhibitor', 'Discharged', 1),
(22, 'Female', 'Diabetes', 9, 3, 'Insulin', 'Discharged', 0),
(83, 'Male', 'COPD', 2, 3, 'ACE Inhibitor', 'Discharged', 1),
(66, 'Female', 'Kidney Disease', 4, 1, 'Antibiotic', 'Transferred', 1),
(68, 'Male', 'Heart Failure', 4, 5, 'Insulin', 'Discharged', 0),
(80, 'Male', 'Diabetes', 4, 1, 'ACE Inhibitor', 'Transferred', 0),
(83, 'Female', 'COPD', 11, 4, 'ACE Inhibitor', 'Transferred', 0),
(48, 'Female', 'Heart Failure', 8, 5, 'Antiviral', 'Discharged', 0),
(73, 'Male', 'Pneumonia', 7, 3, 'Dialysis', 'Discharged', 0),
(48, 'Female', 'Heart Failure', 13, 0, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(82, 'Female', 'Kidney Disease', 10, 5, 'Insulin', 'Discharged', 0),
(53, 'Male', 'Asthma', 11, 1, 'Dialysis', 'Transferred', 1),
(40, 'Male', 'Asthma', 6, 3, 'ACE Inhibitor', 'Transferred', 0),
(21, 'Male', 'Diabetes', 10, 4, 'Insulin', 'Left Against Medical Advice', 1),
(42, 'Male', 'COPD', 6, 3, 'Antiviral', 'Discharged', 1),
(27, 'Male', 'Hypertension', 6, 5, 'Diuretic', 'Transferred', 1),
(36, 'Female', 'Heart Failure', 2, 4, 'Steroid', 'Transferred', 1),
(86, 'Male', 'Hypertension', 14, 4, 'Insulin', 'Transferred', 0),
(83, 'Female', 'Hypertension', 3, 0, 'Antibiotic', 'Discharged', 0),
(60, 'Female', 'Diabetes', 9, 3, 'Antibiotic', 'Left Against Medical Advice', 0),
(58, 'Female', 'Asthma', 10, 1, 'Antiviral', 'Transferred', 0),
(67, 'Female', 'Diabetes', 14, 3, 'Antiviral', 'Transferred', 0),
(42, 'Male', 'COPD', 4, 3, 'Antiviral', 'Left Against Medical Advice', 0),
(30, 'Male', 'Kidney Disease', 13, 0, 'Dialysis', 'Discharged', 1),
(52, 'Male', 'Asthma', 2, 0, 'Dialysis', 'Discharged', 1),
(86, 'Male', 'Heart Failure', 14, 4, 'Antiviral', 'Discharged', 1),
(25, 'Female', 'Pneumonia', 5, 3, 'Dialysis', 'Left Against Medical Advice', 0),
(83, 'Female', 'Pneumonia', 3, 3, 'Steroid', 'Transferred', 1),
(47, 'Female', 'Pneumonia', 6, 5, 'Steroid', 'Left Against Medical Advice', 1),
(40, 'Female', 'Asthma', 14, 5, 'Antibiotic', 'Left Against Medical Advice', 1),
(39, 'Male', 'Hypertension', 12, 2, 'Insulin', 'Left Against Medical Advice', 1),
(40, 'Female', 'Diabetes', 12, 4, 'Inhaler', 'Left Against Medical Advice', 0),
(32, 'Female', 'COPD', 8, 5, 'Dialysis', 'Discharged', 0),
(51, 'Female', 'COPD', 5, 1, 'Antiviral', 'Transferred', 0),
(67, 'Female', 'Kidney Disease', 12, 1, 'ACE Inhibitor', 'Transferred', 0),
(83, 'Male', 'Diabetes', 7, 3, 'Insulin', 'Left Against Medical Advice', 1),
(65, 'Male', 'Kidney Disease', 4, 3, 'Antiviral', 'Transferred', 1),
(38, 'Male', 'Diabetes', 5, 1, 'Diuretic', 'Discharged', 1),
(59, 'Male', 'Asthma', 11, 4, 'Inhaler', 'Discharged', 0),
(20, 'Male', 'Pneumonia', 14, 2, 'Diuretic', 'Left Against Medical Advice', 0),
(56, 'Male', 'COPD', 6, 1, 'Steroid', 'Transferred', 0),
(69, 'Male', 'Hypertension', 6, 4, 'Antiviral', 'Left Against Medical Advice', 0),
(46, 'Female', 'Liver Disease', 14, 1, 'Diuretic', 'Transferred', 0),
(46, 'Male', 'Liver Disease', 2, 3, 'Insulin', 'Transferred', 1),
(39, 'Male', 'Hypertension', 5, 0, 'Dialysis', 'Transferred', 1),
(80, 'Male', 'Liver Disease', 2, 0, 'Inhaler', 'Left Against Medical Advice', 1),
(46, 'Female', 'Liver Disease', 2, 0, 'Antiviral', 'Transferred', 1),
(49, 'Male', 'Hypertension', 8, 0, 'Inhaler', 'Left Against Medical Advice', 0),
(29, 'Female', 'COPD', 7, 3, 'Steroid', 'Discharged', 1),
(27, 'Male', 'Heart Failure', 11, 3, 'Antibiotic', 'Left Against Medical Advice', 1),
(89, 'Female', 'Pneumonia', 14, 2, 'Antiviral', 'Transferred', 1),
(33, 'Male', 'Diabetes', 6, 0, 'Dialysis', 'Left Against Medical Advice', 1),
(61, 'Male', 'COPD', 5, 0, 'Antiviral', 'Transferred', 1),
(69, 'Female', 'COPD', 9, 0, 'Dialysis', 'Discharged', 1),
(88, 'Male', 'Pneumonia', 7, 1, 'Insulin', 'Left Against Medical Advice', 0),
(53, 'Male', 'Diabetes', 8, 3, 'Steroid', 'Transferred', 0),
(81, 'Female', 'Diabetes', 7, 2, 'Antiviral', 'Discharged', 1),
(31, 'Female', 'Liver Disease', 10, 2, 'Inhaler', 'Discharged', 0),
(53, 'Female', 'COPD', 14, 1, 'ACE Inhibitor', 'Discharged', 1),
(32, 'Female', 'Hypertension', 5, 4, 'Antiviral', 'Left Against Medical Advice', 1),
(53, 'Male', 'Hypertension', 10, 5, 'Diuretic', 'Transferred', 0),
(22, 'Male', 'Pneumonia', 3, 1, 'Inhaler', 'Left Against Medical Advice', 0),
(31, 'Female', 'Kidney Disease', 7, 3, 'Diuretic', 'Left Against Medical Advice', 0),
(82, 'Female', 'Diabetes', 4, 5, 'Antibiotic', 'Discharged', 0),
(82, 'Male', 'COPD', 12, 3, 'Antiviral', 'Transferred', 0),
(81, 'Female', 'Asthma', 3, 2, 'Antibiotic', 'Discharged', 1),
(38, 'Male', 'COPD', 3, 0, 'ACE Inhibitor', 'Transferred', 0),
(46, 'Male', 'Diabetes', 14, 1, 'Dialysis', 'Left Against Medical Advice', 1),
(32, 'Male', 'COPD', 5, 4, 'Inhaler', 'Discharged', 1),
(33, 'Female', 'Asthma', 9, 4, 'Steroid', 'Left Against Medical Advice', 0),
(83, 'Female', 'Diabetes', 5, 1, 'Antiviral', 'Left Against Medical Advice', 1),
(52, 'Male', 'Liver Disease', 11, 3, 'Inhaler', 'Discharged', 0),
(42, 'Female', 'Asthma', 13, 3, 'Diuretic', 'Left Against Medical Advice', 1),
(62, 'Female', 'Asthma', 6, 4, 'Dialysis', 'Left Against Medical Advice', 0),
(49, 'Female', 'Heart Failure', 2, 2, 'Steroid', 'Transferred', 0),
(50, 'Male', 'COPD', 8, 2, 'Dialysis', 'Left Against Medical Advice', 0),
(68, 'Female', 'COPD', 5, 5, 'Inhaler', 'Discharged', 0),
(54, 'Female', 'Kidney Disease', 14, 4, 'Steroid', 'Discharged', 0),
(67, 'Male', 'COPD', 7, 1, 'Antiviral', 'Transferred', 1),
(29, 'Male', 'Diabetes', 10, 3, 'Diuretic', 'Left Against Medical Advice', 1),
(66, 'Male', 'Hypertension', 7, 1, 'Dialysis', 'Left Against Medical Advice', 1),
(30, 'Female', 'Asthma', 3, 0, 'Diuretic', 'Discharged', 0),
(66, 'Female', 'COPD', 10, 0, 'Insulin', 'Discharged', 1),
(47, 'Female', 'Asthma', 10, 0, 'Steroid', 'Transferred', 0),
(43, 'Female', 'Heart Failure', 5, 5, 'Dialysis', 'Transferred', 0),
(20, 'Female', 'Heart Failure', 12, 0, 'Dialysis', 'Left Against Medical Advice', 1),
(88, 'Female', 'Hypertension', 3, 0, 'Inhaler', 'Discharged', 1),
(81, 'Female', 'Kidney Disease', 14, 5, 'Antibiotic', 'Discharged', 0),
(87, 'Female', 'Heart Failure', 14, 1, 'Insulin', 'Transferred', 1),
(26, 'Female', 'Pneumonia', 7, 3, 'ACE Inhibitor', 'Discharged', 0),
(41, 'Male', 'Heart Failure', 7, 4, 'Steroid', 'Discharged', 1),
(54, 'Male', 'Liver Disease', 6, 2, 'Antiviral', 'Transferred', 0),
(89, 'Female', 'Hypertension', 5, 3, 'Insulin', 'Discharged', 1),
(60, 'Female', 'Diabetes', 7, 1, 'Dialysis', 'Transferred', 0),
(61, 'Female', 'Hypertension', 4, 3, 'Inhaler', 'Left Against Medical Advice', 1),
(67, 'Male', 'Heart Failure', 2, 5, 'Antibiotic', 'Discharged', 0),
(79, 'Female', 'Pneumonia', 12, 0, 'Antibiotic', 'Discharged', 0),
(23, 'Male', 'Hypertension', 11, 2, 'Antiviral', 'Transferred', 0),
(87, 'Male', 'Liver Disease', 12, 5, 'Dialysis', 'Transferred', 0),
(46, 'Male', 'Hypertension', 3, 0, 'Diuretic', 'Discharged', 0),
(70, 'Female', 'Heart Failure', 14, 2, 'Inhaler', 'Transferred', 1),
(36, 'Female', 'Diabetes', 2, 4, 'Antibiotic', 'Discharged', 0),
(30, 'Male', 'Pneumonia', 13, 5, 'Diuretic', 'Discharged', 1),
(75, 'Female', 'Kidney Disease', 9, 2, 'Antibiotic', 'Transferred', 0),
(85, 'Female', 'COPD', 14, 2, 'Antiviral', 'Left Against Medical Advice', 0),
(37, 'Female', 'Liver Disease', 11, 5, 'Dialysis', 'Left Against Medical Advice', 1),
(76, 'Female', 'Pneumonia', 10, 5, 'Steroid', 'Transferred', 1),
(58, 'Male', 'Heart Failure', 12, 4, 'ACE Inhibitor', 'Discharged', 1),
(53, 'Male', 'Diabetes', 9, 5, 'Insulin', 'Transferred', 0),
(40, 'Male', 'Heart Failure', 3, 3, 'Antibiotic', 'Transferred', 0),
(82, 'Male', 'Hypertension', 12, 2, 'Dialysis', 'Transferred', 0),
(87, 'Female', 'Kidney Disease', 14, 1, 'Antiviral', 'Transferred', 0),
(39, 'Male', 'Kidney Disease', 11, 0, 'Steroid', 'Discharged', 0),
(31, 'Male', 'COPD', 13, 1, 'Insulin', 'Left Against Medical Advice', 0),
(26, 'Male', 'Heart Failure', 8, 4, 'Antibiotic', 'Discharged', 1),
(26, 'Female', 'Pneumonia', 8, 4, 'Steroid', 'Transferred', 1),
(52, 'Male', 'Hypertension', 4, 5, 'Steroid', 'Transferred', 0),
(70, 'Male', 'Hypertension', 14, 2, 'Antiviral', 'Transferred', 1),
(64, 'Female', 'Liver Disease', 9, 2, 'Insulin', 'Transferred', 0),
(34, 'Female', 'Diabetes', 5, 5, 'Dialysis', 'Left Against Medical Advice', 0),
(29, 'Male', 'Liver Disease', 9, 2, 'Inhaler', 'Left Against Medical Advice', 0),
(32, 'Female', 'Asthma', 5, 3, 'ACE Inhibitor', 'Discharged', 1),
(71, 'Female', 'Heart Failure', 6, 5, 'Steroid', 'Left Against Medical Advice', 0),
(73, 'Male', 'Kidney Disease', 5, 5, 'Inhaler', 'Discharged', 0),
(41, 'Male', 'Pneumonia', 3, 5, 'Antiviral', 'Transferred', 1),
(34, 'Male', 'Kidney Disease', 5, 1, 'Dialysis', 'Transferred', 1),
(29, 'Female', 'Diabetes', 8, 0, 'Insulin', 'Discharged', 0),
(82, 'Female', 'COPD', 4, 4, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(62, 'Male', 'Liver Disease', 2, 4, 'ACE Inhibitor', 'Discharged', 1),
(48, 'Male', 'Heart Failure', 3, 2, 'Dialysis', 'Discharged', 1),
(57, 'Female', 'Heart Failure', 3, 4, 'Diuretic', 'Left Against Medical Advice', 1),
(59, 'Female', 'Pneumonia', 12, 2, 'Diuretic', 'Discharged', 1),
(90, 'Male', 'COPD', 10, 5, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(23, 'Male', 'Kidney Disease', 9, 3, 'Diuretic', 'Transferred', 1),
(40, 'Female', 'Diabetes', 5, 3, 'ACE Inhibitor', 'Discharged', 1),
(57, 'Female', 'Pneumonia', 10, 2, 'Antibiotic', 'Transferred', 1),
(56, 'Female', 'Asthma', 12, 0, 'Steroid', 'Discharged', 1),
(23, 'Male', 'Asthma', 5, 3, 'Steroid', 'Discharged', 0),
(50, 'Female', 'Diabetes', 2, 3, 'Steroid', 'Discharged', 0),
(84, 'Male', 'Diabetes', 8, 4, 'Insulin', 'Transferred', 1),
(32, 'Female', 'Pneumonia', 13, 3, 'Steroid', 'Transferred', 0),
(44, 'Male', 'Heart Failure', 5, 5, 'Diuretic', 'Discharged', 1),
(71, 'Male', 'Asthma', 14, 3, 'Insulin', 'Left Against Medical Advice', 1),
(50, 'Male', 'COPD', 6, 2, 'Steroid', 'Transferred', 1),
(49, 'Male', 'Asthma', 5, 4, 'Diuretic', 'Discharged', 0),
(44, 'Female', 'Heart Failure', 9, 4, 'Antiviral', 'Left Against Medical Advice', 1),
(68, 'Female', 'COPD', 14, 0, 'ACE Inhibitor', 'Discharged', 1),
(79, 'Female', 'COPD', 5, 0, 'Inhaler', 'Left Against Medical Advice', 0),
(90, 'Female', 'Pneumonia', 5, 3, 'Inhaler', 'Discharged', 0),
(60, 'Female', 'Kidney Disease', 11, 1, 'ACE Inhibitor', 'Left Against Medical Advice', 0),
(33, 'Male', 'Diabetes', 8, 1, 'Dialysis', 'Transferred', 0),
(25, 'Female', 'Pneumonia', 12, 2, 'Dialysis', 'Transferred', 1),
(84, 'Female', 'Liver Disease', 8, 2, 'Inhaler', 'Left Against Medical Advice', 1),
(80, 'Female', 'Kidney Disease', 9, 3, 'Diuretic', 'Left Against Medical Advice', 0),
(23, 'Female', 'Hypertension', 10, 3, 'Inhaler', 'Transferred', 1),
(22, 'Male', 'Asthma', 6, 1, 'Antibiotic', 'Left Against Medical Advice', 1),
(44, 'Male', 'Heart Failure', 10, 0, 'Antibiotic', 'Transferred', 0),
(68, 'Female', 'Diabetes', 9, 0, 'Antibiotic', 'Discharged', 1),
(63, 'Male', 'Liver Disease', 4, 3, 'Inhaler', 'Transferred', 1),
(21, 'Male', 'Asthma', 10, 5, 'Antibiotic', 'Left Against Medical Advice', 1),
(73, 'Female', 'Pneumonia', 13, 0, 'Steroid', 'Left Against Medical Advice', 1),
(69, 'Male', 'Hypertension', 4, 2, 'Antiviral', 'Transferred', 1),
(37, 'Female', 'Pneumonia', 14, 0, 'ACE Inhibitor', 'Discharged', 0),
(36, 'Male', 'Liver Disease', 6, 5, 'Antiviral', 'Transferred', 0),
(66, 'Male', 'Diabetes', 5, 4, 'Diuretic', 'Left Against Medical Advice', 0),
(35, 'Male', 'COPD', 5, 3, 'ACE Inhibitor', 'Discharged', 1),
(59, 'Male', 'Pneumonia', 10, 4, 'ACE Inhibitor', 'Transferred', 0),
(31, 'Male', 'Kidney Disease', 11, 5, 'Inhaler', 'Transferred', 1),
(48, 'Female', 'Pneumonia', 3, 1, 'Inhaler', 'Discharged', 1),
(31, 'Male', 'COPD', 7, 3, 'Steroid', 'Discharged', 1),
(20, 'Female', 'Pneumonia', 6, 2, 'Dialysis', 'Left Against Medical Advice', 1),
(81, 'Male', 'Asthma', 7, 4, 'Antiviral', 'Discharged', 1),
(33, 'Male', 'Asthma', 14, 0, 'ACE Inhibitor', 'Left Against Medical Advice', 1),
(61, 'Female', 'Pneumonia', 10, 2, 'Antiviral', 'Transferred', 0),
(28, 'Male', 'Heart Failure', 10, 2, 'Antiviral', 'Left Against Medical Advice', 0),
(59, 'Male', 'Heart Failure', 2, 1, 'Steroid', 'Left Against Medical Advice', 1),
(85, 'Male', 'Kidney Disease', 7, 1, 'ACE Inhibitor', 'Discharged', 0),
(33, 'Male', 'Heart Failure', 8, 3, 'Dialysis', 'Transferred', 0),
(39, 'Female', 'Pneumonia', 5, 0, 'Diuretic', 'Left Against Medical Advice', 1),
(21, 'Male', 'Hypertension', 5, 4, 'Inhaler', 'Transferred', 0),
(56, 'Female', 'Kidney Disease', 4, 2, 'Inhaler', 'Left Against Medical Advice', 0),
(31, 'Male', 'Hypertension', 14, 0, 'Insulin', 'Discharged', 1),
(55, 'Female', 'Liver Disease', 13, 5, 'Antiviral', 'Transferred', 1),
(52, 'Female', 'Pneumonia', 8, 1, 'Inhaler', 'Discharged', 1),
(66, 'Female', 'COPD', 8, 1, 'Antibiotic', 'Discharged', 0),
(53, 'Female', 'Liver Disease', 3, 2, 'Insulin', 'Discharged', 0),
(48, 'Male', 'Liver Disease', 7, 3, 'Antibiotic', 'Transferred', 0),
(70, 'Male', 'Pneumonia', 5, 2, 'Diuretic', 'Transferred', 1),
(61, 'Male', 'Asthma', 11, 0, 'Antibiotic', 'Transferred', 0),
(48, 'Male', 'Liver Disease', 11, 2, 'Diuretic', 'Discharged', 1),
(40, 'Male', 'Liver Disease', 12, 5, 'Steroid', 'Left Against Medical Advice', 1),
(53, 'Female', 'Kidney Disease', 13, 5, 'ACE Inhibitor', 'Transferred', 0),
(31, 'Male', 'Heart Failure', 2, 5, 'Diuretic', 'Discharged', 0);
